// Code generated by generate-crossplane.ts — DO NOT EDIT.

package controller

import (
	"context"
	"fmt"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/controller"
	"github.com/crossplane/crossplane-runtime/pkg/event"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/pkg/resource"
	"github.com/pgbeam/provider-pgbeam/apis/v1alpha1"
	pgbeam "go.pgbeam.com/sdk"
	ctrl "sigs.k8s.io/controller-runtime"
	"time"
)

const (
	errNotAgentCredential     = "managed resource is not a AgentCredential"
	errAgentCredentialCreate  = "cannot create AgentCredential"
	errAgentCredentialUpdate  = "cannot update AgentCredential"
	errAgentCredentialDelete  = "cannot delete AgentCredential"
	errAgentCredentialObserve = "cannot observe AgentCredential"
)

func SetupAgentCredential(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.AgentCredentialGroupKind)
	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		For(&v1alpha1.AgentCredential{}).
		WithOptions(o.ForControllerRuntime()).
		Complete(managed.NewReconciler(mgr,
			resource.ManagedKind(v1alpha1.AgentCredentialGroupVersionKind),
			managed.WithExternalConnecter(&agentCredentialConnecter{
				connector: connector{
					kube:  mgr.GetClient(),
					usage: resource.NewProviderConfigUsageTracker(mgr.GetClient(), &v1alpha1.ProviderConfigUsage{}),
				},
			}),
			managed.WithLogger(o.Logger.WithValues("controller", name)),
			managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))),
		))
}

type agentCredentialConnecter struct{ connector }

func (c *agentCredentialConnecter) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cl, err := c.getClient(ctx, mg)
	if err != nil {
		return nil, err
	}
	return &agentCredentialExternal{client: cl}, nil
}

type agentCredentialExternal struct{ client *pgbeam.Client }

func (e *agentCredentialExternal) Disconnect(_ context.Context) error { return nil }

func (e *agentCredentialExternal) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.AgentCredential)
	if !ok {
		return managed.ExternalObservation{}, fmt.Errorf(errNotAgentCredential)
	}

	externalName := meta.GetExternalName(cr)
	if externalName == "" {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	agentCredential, err := e.client.Agents.GetAgentCredential(ctx, cr.Spec.ForProvider.ProjectID, externalName)
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, fmt.Errorf("%s: %w", errAgentCredentialObserve, err)
	}

	cr.Status.AtProvider = agentCredentialObservation(agentCredential)
	cr.SetConditions(xpv1.Available())

	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: isAgentCredentialUpToDate(cr.Spec.ForProvider, agentCredential),
	}, nil
}
func (e *agentCredentialExternal) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.AgentCredential)
	if !ok {
		return managed.ExternalCreation{}, fmt.Errorf(errNotAgentCredential)
	}

	fp := cr.Spec.ForProvider

	req := pgbeam.CreateAgentCredentialRequest{
		PolicyProfileId: fp.PolicyProfileID,
		Name:            fp.Name,
	}
	if fp.PrincipalType != "" {
		v := pgbeam.CreateAgentCredentialRequestPrincipalType(fp.PrincipalType)
		req.PrincipalType = &v
	}
	if fp.ExpiresAt != "" {
		expiresAtTime, err := time.Parse(time.RFC3339, fp.ExpiresAt)
		if err != nil {
			return managed.ExternalCreation{}, fmt.Errorf("%s: invalid expires_at: %w", errAgentCredentialCreate, err)
		}
		req.ExpiresAt = &expiresAtTime
	}

	resp, err := e.client.Agents.CreateAgentCredential(ctx, fp.ProjectID, req)
	if err != nil {
		return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errAgentCredentialCreate, err)
	}

	// Rate-limit fields are not supported in CreateAgentCredentialRequest.
	// If specified, issue an immediate update after creation.
	updateReq := pgbeam.UpdateAgentCredentialStatusRequest{}
	needsPostCreateUpdate := false
	if fp.Status != "" {
		v := pgbeam.UpdateAgentCredentialStatusRequestStatus(fp.Status)
		updateReq.Status = v
		needsPostCreateUpdate = true
	}
	if needsPostCreateUpdate {
		updated, err := e.client.Agents.UpdateAgentCredentialStatus(ctx, fp.ProjectID, resp.Credential.Id, updateReq)
		if err != nil {
			return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errAgentCredentialUpdate, err)
		}
		resp.Credential = *updated
	}

	meta.SetExternalName(cr, resp.Credential.Id)
	cr.Status.AtProvider = agentCredentialObservation(&resp.Credential)
	cr.Status.AtProvider.McpURL = resp.McpUrl

	connDetails := managed.ConnectionDetails{}
	if resp.ConnectionString != "" {
		connDetails["connectionString"] = []byte(resp.ConnectionString)
	}
	if resp.McpToken != "" {
		connDetails["mcpToken"] = []byte(resp.McpToken)
	}
	return managed.ExternalCreation{ConnectionDetails: connDetails}, nil
}
func (e *agentCredentialExternal) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*v1alpha1.AgentCredential)
	if !ok {
		return managed.ExternalUpdate{}, fmt.Errorf(errNotAgentCredential)
	}

	fp := cr.Spec.ForProvider
	externalName := meta.GetExternalName(cr)

	agentCredential, err := e.client.Agents.GetAgentCredential(ctx, cr.Spec.ForProvider.ProjectID, externalName)
	if err != nil {
		return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errAgentCredentialObserve, err)
	}

	req := pgbeam.UpdateAgentCredentialStatusRequest{}
	needsUpdate := false

	if fp.Status != "" && fp.Status != string(agentCredential.Status) {
		v := pgbeam.UpdateAgentCredentialStatusRequestStatus(fp.Status)
		req.Status = v
		needsUpdate = true
	}

	if needsUpdate {
		if _, err := e.client.Agents.UpdateAgentCredentialStatus(ctx, fp.ProjectID, externalName, req); err != nil {
			return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errAgentCredentialUpdate, err)
		}
	}
	return managed.ExternalUpdate{}, nil
}
func (e *agentCredentialExternal) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*v1alpha1.AgentCredential)
	if !ok {
		return managed.ExternalDelete{}, fmt.Errorf(errNotAgentCredential)
	}
	if err := e.client.Agents.RevokeAgentCredential(ctx, cr.Spec.ForProvider.ProjectID, meta.GetExternalName(cr)); err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalDelete{}, nil
		}
		return managed.ExternalDelete{}, fmt.Errorf("%s: %w", errAgentCredentialDelete, err)
	}
	return managed.ExternalDelete{}, nil
}
func agentCredentialObservation(a *pgbeam.AgentCredential) v1alpha1.AgentCredentialAtProvider {
	obs := v1alpha1.AgentCredentialAtProvider{
		ID:         a.Id,
		PgUsername: a.PgUsername,
		CreatedAt:  a.CreatedAt.Format(time.RFC3339),
		UpdatedAt:  a.UpdatedAt.Format(time.RFC3339),
	}
	if a.AuthMethod != nil {
		obs.AuthMethod = string(*a.AuthMethod)
	}
	if a.LastUsedAt != nil {
		obs.LastUsedAt = a.LastUsedAt.Format(time.RFC3339)
	}
	return obs
}
func isAgentCredentialUpToDate(fp v1alpha1.AgentCredentialForProvider, a *pgbeam.AgentCredential) bool {
	if fp.Status != "" {
		if fp.Status != string(a.Status) {
			return false
		}
	}
	return true
}
