// Code generated by generate-crossplane.ts — DO NOT EDIT.

package controller

import (
	"context"
	"fmt"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/controller"
	"github.com/crossplane/crossplane-runtime/pkg/event"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/pkg/resource"
	"github.com/sferarc/pgbeam-crossplane/apis/v1alpha1"
	pgbeam "go.pgbeam.com/sdk"
	ctrl "sigs.k8s.io/controller-runtime"
	"time"
)

const (
	errNotAnomalyRule     = "managed resource is not a AnomalyRule"
	errAnomalyRuleCreate  = "cannot create AnomalyRule"
	errAnomalyRuleUpdate  = "cannot update AnomalyRule"
	errAnomalyRuleDelete  = "cannot delete AnomalyRule"
	errAnomalyRuleObserve = "cannot observe AnomalyRule"
)

func SetupAnomalyRule(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.AnomalyRuleGroupKind)
	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		For(&v1alpha1.AnomalyRule{}).
		WithOptions(o.ForControllerRuntime()).
		Complete(managed.NewReconciler(mgr,
			resource.ManagedKind(v1alpha1.AnomalyRuleGroupVersionKind),
			managed.WithExternalConnecter(&anomalyRuleConnecter{
				connector: connector{
					kube:  mgr.GetClient(),
					usage: resource.NewProviderConfigUsageTracker(mgr.GetClient(), &v1alpha1.ProviderConfigUsage{}),
				},
			}),
			managed.WithLogger(o.Logger.WithValues("controller", name)),
			managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))),
		))
}

type anomalyRuleConnecter struct{ connector }

func (c *anomalyRuleConnecter) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cl, err := c.getClient(ctx, mg)
	if err != nil {
		return nil, err
	}
	return &anomalyRuleExternal{client: cl}, nil
}

type anomalyRuleExternal struct{ client *pgbeam.Client }

func (e *anomalyRuleExternal) Disconnect(_ context.Context) error { return nil }

func (e *anomalyRuleExternal) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.AnomalyRule)
	if !ok {
		return managed.ExternalObservation{}, fmt.Errorf(errNotAnomalyRule)
	}

	externalName := meta.GetExternalName(cr)
	if externalName == "" {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	anomalyRule, err := e.client.Anomalies.GetAnomalyRule(ctx, cr.Spec.ForProvider.ProjectID, externalName)
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, fmt.Errorf("%s: %w", errAnomalyRuleObserve, err)
	}

	cr.Status.AtProvider = anomalyRuleObservation(anomalyRule)
	cr.SetConditions(xpv1.Available())

	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: isAnomalyRuleUpToDate(cr.Spec.ForProvider, anomalyRule),
	}, nil
}
func (e *anomalyRuleExternal) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.AnomalyRule)
	if !ok {
		return managed.ExternalCreation{}, fmt.Errorf(errNotAnomalyRule)
	}

	fp := cr.Spec.ForProvider
	req := pgbeam.AnomalyRuleInput{
		Metric: pgbeam.AnomalyMetric(fp.Metric),
	}
	if fp.CredentialID != nil {
		req.CredentialId = fp.CredentialID
	}
	if fp.SigmaThreshold != nil {
		req.SigmaThreshold = fp.SigmaThreshold
	}
	if fp.Floor != nil {
		req.Floor = fp.Floor
	}
	if fp.Enabled != nil {
		req.Enabled = fp.Enabled
	}

	anomalyRule, err := e.client.Anomalies.CreateAnomalyRule(ctx, fp.ProjectID, req)
	if err != nil {
		return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errAnomalyRuleCreate, err)
	}

	meta.SetExternalName(cr, anomalyRule.Id)
	cr.Status.AtProvider = anomalyRuleObservation(anomalyRule)
	return managed.ExternalCreation{}, nil
}
func (e *anomalyRuleExternal) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*v1alpha1.AnomalyRule)
	if !ok {
		return managed.ExternalUpdate{}, fmt.Errorf(errNotAnomalyRule)
	}

	fp := cr.Spec.ForProvider
	externalName := meta.GetExternalName(cr)

	anomalyRule, err := e.client.Anomalies.GetAnomalyRule(ctx, cr.Spec.ForProvider.ProjectID, externalName)
	if err != nil {
		return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errAnomalyRuleObserve, err)
	}

	req := pgbeam.AnomalyRuleInput{}
	needsUpdate := !isAnomalyRuleUpToDate(fp, anomalyRule)

	if fp.CredentialID != nil {
		req.CredentialId = fp.CredentialID
	}
	if fp.Metric != "" {
		v := pgbeam.AnomalyMetric(fp.Metric)
		req.Metric = v
	}
	if fp.SigmaThreshold != nil {
		req.SigmaThreshold = fp.SigmaThreshold
	}
	if fp.Floor != nil {
		req.Floor = fp.Floor
	}
	if fp.Enabled != nil {
		req.Enabled = fp.Enabled
	}

	if needsUpdate {
		if _, err := e.client.Anomalies.UpdateAnomalyRule(ctx, fp.ProjectID, externalName, req); err != nil {
			return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errAnomalyRuleUpdate, err)
		}
	}
	return managed.ExternalUpdate{}, nil
}
func (e *anomalyRuleExternal) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*v1alpha1.AnomalyRule)
	if !ok {
		return managed.ExternalDelete{}, fmt.Errorf(errNotAnomalyRule)
	}
	if err := e.client.Anomalies.DeleteAnomalyRule(ctx, cr.Spec.ForProvider.ProjectID, meta.GetExternalName(cr)); err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalDelete{}, nil
		}
		return managed.ExternalDelete{}, fmt.Errorf("%s: %w", errAnomalyRuleDelete, err)
	}
	return managed.ExternalDelete{}, nil
}
func anomalyRuleObservation(a *pgbeam.AnomalyRule) v1alpha1.AnomalyRuleAtProvider {
	obs := v1alpha1.AnomalyRuleAtProvider{
		ID:        a.Id,
		CreatedAt: a.CreatedAt.Format(time.RFC3339),
		UpdatedAt: a.UpdatedAt.Format(time.RFC3339),
	}
	return obs
}
func isAnomalyRuleUpToDate(fp v1alpha1.AnomalyRuleForProvider, a *pgbeam.AnomalyRule) bool {
	if fp.CredentialID != nil && (a.CredentialId == nil || *fp.CredentialID != *a.CredentialId) {
		return false
	}
	if fp.Metric != string(a.Metric) {
		return false
	}
	if fp.SigmaThreshold != nil && (a.SigmaThreshold == nil || *fp.SigmaThreshold != *a.SigmaThreshold) {
		return false
	}
	if fp.Floor != nil && (a.Floor == nil || *fp.Floor != *a.Floor) {
		return false
	}
	if fp.Enabled != nil && (*fp.Enabled != a.Enabled) {
		return false
	}
	return true
}
