// Code generated by generate-crossplane.ts — DO NOT EDIT.

package controller

import (
	"context"
	"fmt"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/controller"
	"github.com/crossplane/crossplane-runtime/pkg/event"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/pkg/resource"
	pgbeam "github.com/pgbeam/pgbeam-go"
	"github.com/pgbeam/provider-pgbeam/apis/v1alpha1"
	ctrl "sigs.k8s.io/controller-runtime"
	"time"
)

const (
	errNotCacheRule     = "managed resource is not a CacheRule"
	errCacheRuleCreate  = "cannot create CacheRule"
	errCacheRuleUpdate  = "cannot update CacheRule"
	errCacheRuleDelete  = "cannot soft-delete CacheRule"
	errCacheRuleObserve = "cannot observe CacheRule"
)

func SetupCacheRule(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.CacheRuleGroupKind)
	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		For(&v1alpha1.CacheRule{}).
		WithOptions(o.ForControllerRuntime()).
		Complete(managed.NewReconciler(mgr,
			resource.ManagedKind(v1alpha1.CacheRuleGroupVersionKind),
			managed.WithExternalConnecter(&cacheRuleConnecter{
				connector: connector{
					kube:  mgr.GetClient(),
					usage: resource.NewProviderConfigUsageTracker(mgr.GetClient(), &v1alpha1.ProviderConfigUsage{}),
				},
			}),
			managed.WithLogger(o.Logger.WithValues("controller", name)),
			managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))),
		))
}

type cacheRuleConnecter struct{ connector }

func (c *cacheRuleConnecter) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cl, err := c.getClient(ctx, mg)
	if err != nil {
		return nil, err
	}
	return &cacheRuleExternal{client: cl}, nil
}

type cacheRuleExternal struct{ client *pgbeam.Client }

func (e *cacheRuleExternal) Disconnect(_ context.Context) error { return nil }

func (e *cacheRuleExternal) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.CacheRule)
	if !ok {
		return managed.ExternalObservation{}, fmt.Errorf(errNotCacheRule)
	}

	externalName := meta.GetExternalName(cr)
	if externalName == "" {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	// No individual Get endpoint; list and filter by QueryHash with pagination.
	cacheRule, err := e.getCacheRule(ctx, cr.Spec.ForProvider.ProjectID, cr.Spec.ForProvider.DatabaseID, cr.Spec.ForProvider.QueryHash)
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, fmt.Errorf("%s: %w", errCacheRuleObserve, err)
	}

	cr.Status.AtProvider = cacheRuleObservation(cacheRule)
	cr.SetConditions(xpv1.Available())

	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: isCacheRuleUpToDate(cr.Spec.ForProvider, cacheRule),
	}, nil
}
func (e *cacheRuleExternal) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.CacheRule)
	if !ok {
		return managed.ExternalCreation{}, fmt.Errorf(errNotCacheRule)
	}

	fp := cr.Spec.ForProvider
	resp, err := e.client.Projects.UpdateCacheRule(ctx, fp.ProjectID, fp.DatabaseID, fp.QueryHash, pgbeam.UpdateCacheRuleRequest{
		CacheEnabled:    fp.CacheEnabled,
		CacheTtlSeconds: fp.CacheTTLSeconds,
		CacheSwrSeconds: fp.CacheSWRSeconds,
	})
	if err != nil {
		return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errCacheRuleCreate, err)
	}

	compositeID := fmt.Sprintf("%s/%s/%s", fp.ProjectID, fp.DatabaseID, fp.QueryHash)
	meta.SetExternalName(cr, compositeID)
	cr.Status.AtProvider = cacheRuleObservation(&resp.Entry)
	return managed.ExternalCreation{}, nil
}
func (e *cacheRuleExternal) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*v1alpha1.CacheRule)
	if !ok {
		return managed.ExternalUpdate{}, fmt.Errorf(errNotCacheRule)
	}

	fp := cr.Spec.ForProvider
	if _, err := e.client.Projects.UpdateCacheRule(ctx, fp.ProjectID, fp.DatabaseID, fp.QueryHash, pgbeam.UpdateCacheRuleRequest{
		CacheEnabled:    fp.CacheEnabled,
		CacheTtlSeconds: fp.CacheTTLSeconds,
		CacheSwrSeconds: fp.CacheSWRSeconds,
	}); err != nil {
		return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errCacheRuleUpdate, err)
	}
	return managed.ExternalUpdate{}, nil
}
func (e *cacheRuleExternal) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*v1alpha1.CacheRule)
	if !ok {
		return managed.ExternalDelete{}, fmt.Errorf(errNotCacheRule)
	}

	fp := cr.Spec.ForProvider
	// Soft delete: disable by setting cache_enabled=false.
	if _, err := e.client.Projects.UpdateCacheRule(ctx, fp.ProjectID, fp.DatabaseID, fp.QueryHash, pgbeam.UpdateCacheRuleRequest{
		CacheEnabled: false,
	}); err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalDelete{}, nil
		}
		return managed.ExternalDelete{}, fmt.Errorf("%s: %w", errCacheRuleDelete, err)
	}
	return managed.ExternalDelete{}, nil
}

// getCacheRule paginates through ListCacheRules to find a cache rule by QueryHash.
func (e *cacheRuleExternal) getCacheRule(ctx context.Context, projectID string, databaseID string, queryHash string) (*pgbeam.CacheRuleEntry, error) {
	var pageToken *string
	for {
		params := &pgbeam.ListCacheRulesParams{PageToken: pageToken}
		resp, err := e.client.Projects.ListCacheRules(ctx, projectID, databaseID, params)
		if err != nil {
			return nil, err
		}
		for i := range resp.Entries {
			if resp.Entries[i].QueryHash == queryHash {
				return &resp.Entries[i], nil
			}
		}
		if resp.NextPageToken == nil || *resp.NextPageToken == "" {
			break
		}
		pageToken = resp.NextPageToken
	}
	return nil, &pgbeam.APIError{StatusCode: 404, Status: "Not Found", Body: fmt.Sprintf("cache rule %s not found in database %s", queryHash, databaseID)}
}
func cacheRuleObservation(c *pgbeam.CacheRuleEntry) v1alpha1.CacheRuleAtProvider {
	obs := v1alpha1.CacheRuleAtProvider{
		QueryHash:        c.QueryHash,
		NormalizedSQL:    c.NormalizedSql,
		QueryType:        string(c.QueryType),
		CallCount:        c.CallCount,
		AvgLatencyMs:     c.AvgLatencyMs,
		P95LatencyMs:     c.P95LatencyMs,
		AvgResponseBytes: c.AvgResponseBytes,
		StabilityRate:    c.StabilityRate,
		Recommendation:   string(c.Recommendation),
		FirstSeenAt:      c.FirstSeenAt.Format(time.RFC3339),
		LastSeenAt:       c.LastSeenAt.Format(time.RFC3339),
	}
	return obs
}
func isCacheRuleUpToDate(fp v1alpha1.CacheRuleForProvider, c *pgbeam.CacheRuleEntry) bool {
	if fp.CacheEnabled != c.CacheEnabled {
		return false
	}
	if fp.CacheTTLSeconds != nil && (c.CacheTtlSeconds == nil || *fp.CacheTTLSeconds != *c.CacheTtlSeconds) {
		return false
	}
	if fp.CacheSWRSeconds != nil && (c.CacheSwrSeconds == nil || *fp.CacheSWRSeconds != *c.CacheSwrSeconds) {
		return false
	}
	return true
}
