// Code generated by generate-crossplane.ts — DO NOT EDIT.

package controller

import (
	"context"
	"fmt"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/controller"
	"github.com/crossplane/crossplane-runtime/pkg/event"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/pkg/resource"
	pgbeam "github.com/pgbeam/pgbeam-go"
	"github.com/pgbeam/provider-pgbeam/apis/v1alpha1"
	ctrl "sigs.k8s.io/controller-runtime"
	"time"
)

const (
	errNotCustomDomain     = "managed resource is not a CustomDomain"
	errCustomDomainCreate  = "cannot create CustomDomain"
	errCustomDomainUpdate  = "CustomDomain is fully immutable and cannot be updated; delete and recreate"
	errCustomDomainDelete  = "cannot delete CustomDomain"
	errCustomDomainObserve = "cannot observe CustomDomain"
)

func SetupCustomDomain(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.CustomDomainGroupKind)
	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		For(&v1alpha1.CustomDomain{}).
		WithOptions(o.ForControllerRuntime()).
		Complete(managed.NewReconciler(mgr,
			resource.ManagedKind(v1alpha1.CustomDomainGroupVersionKind),
			managed.WithExternalConnecter(&customDomainConnecter{
				connector: connector{
					kube:  mgr.GetClient(),
					usage: resource.NewProviderConfigUsageTracker(mgr.GetClient(), &v1alpha1.ProviderConfigUsage{}),
				},
			}),
			managed.WithLogger(o.Logger.WithValues("controller", name)),
			managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))),
		))
}

type customDomainConnecter struct{ connector }

func (c *customDomainConnecter) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cl, err := c.getClient(ctx, mg)
	if err != nil {
		return nil, err
	}
	return &customDomainExternal{client: cl}, nil
}

type customDomainExternal struct{ client *pgbeam.Client }

func (e *customDomainExternal) Disconnect(_ context.Context) error { return nil }

func (e *customDomainExternal) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.CustomDomain)
	if !ok {
		return managed.ExternalObservation{}, fmt.Errorf(errNotCustomDomain)
	}

	externalName := meta.GetExternalName(cr)
	if externalName == "" {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	// No individual Get endpoint; list and filter by ID with pagination.
	customDomain, err := e.getCustomDomain(ctx, cr.Spec.ForProvider.ProjectID, externalName)
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, fmt.Errorf("%s: %w", errCustomDomainObserve, err)
	}

	cr.Status.AtProvider = v1alpha1.CustomDomainAtProvider{
		ID:            customDomain.Id,
		VerifiedAt:    customDomain.VerifiedAt.Format(time.RFC3339),
		TLSCertExpiry: customDomain.TlsCertExpiry.Format(time.RFC3339),
		CreatedAt:     customDomain.CreatedAt.Format(time.RFC3339),
		UpdatedAt:     customDomain.UpdatedAt.Format(time.RFC3339),
	}
	cr.SetConditions(xpv1.Available())

	return managed.ExternalObservation{ResourceExists: true, ResourceUpToDate: true}, nil
}
func (e *customDomainExternal) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.CustomDomain)
	if !ok {
		return managed.ExternalCreation{}, fmt.Errorf(errNotCustomDomain)
	}

	fp := cr.Spec.ForProvider
	req := pgbeam.CreateCustomDomainRequest{
		Domain: fp.Domain,
	}

	customDomain, err := e.client.Projects.CreateCustomDomain(ctx, fp.ProjectID, req)
	if err != nil {
		return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errCustomDomainCreate, err)
	}

	meta.SetExternalName(cr, customDomain.Id)
	cr.Status.AtProvider = v1alpha1.CustomDomainAtProvider{
		ID:            customDomain.Id,
		VerifiedAt:    customDomain.VerifiedAt.Format(time.RFC3339),
		TLSCertExpiry: customDomain.TlsCertExpiry.Format(time.RFC3339),
		CreatedAt:     customDomain.CreatedAt.Format(time.RFC3339),
		UpdatedAt:     customDomain.UpdatedAt.Format(time.RFC3339),
	}

	connDetails := managed.ConnectionDetails{}
	if customDomain.DnsVerificationToken != "" {
		connDetails["dnsVerificationToken"] = []byte(customDomain.DnsVerificationToken)
	}
	return managed.ExternalCreation{ConnectionDetails: connDetails}, nil
}
func (e *customDomainExternal) Update(_ context.Context, _ resource.Managed) (managed.ExternalUpdate, error) {
	return managed.ExternalUpdate{}, fmt.Errorf(errCustomDomainUpdate)
}
func (e *customDomainExternal) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*v1alpha1.CustomDomain)
	if !ok {
		return managed.ExternalDelete{}, fmt.Errorf(errNotCustomDomain)
	}
	if err := e.client.Projects.DeleteCustomDomain(ctx, cr.Spec.ForProvider.ProjectID, meta.GetExternalName(cr)); err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalDelete{}, nil
		}
		return managed.ExternalDelete{}, fmt.Errorf("%s: %w", errCustomDomainDelete, err)
	}
	return managed.ExternalDelete{}, nil
}

// getCustomDomain paginates through ListCustomDomains to find a custom domain by Id.
func (e *customDomainExternal) getCustomDomain(ctx context.Context, projectID string, id string) (*pgbeam.CustomDomain, error) {
	var pageToken *string
	for {
		params := &pgbeam.ListCustomDomainsParams{PageToken: pageToken}
		resp, err := e.client.Projects.ListCustomDomains(ctx, projectID, params)
		if err != nil {
			return nil, err
		}
		for i := range resp.Domains {
			if resp.Domains[i].Id == id {
				return &resp.Domains[i], nil
			}
		}
		if resp.NextPageToken == nil || *resp.NextPageToken == "" {
			break
		}
		pageToken = resp.NextPageToken
	}
	return nil, &pgbeam.APIError{StatusCode: 404, Status: "Not Found", Body: fmt.Sprintf("custom domain %s not found in project %s", id, projectID)}
}
