// Code generated by generate-crossplane.ts — DO NOT EDIT.

package controller

import (
	"context"
	"fmt"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/controller"
	"github.com/crossplane/crossplane-runtime/pkg/event"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/pkg/resource"
	pgbeam "github.com/pgbeam/pgbeam-go"
	"github.com/pgbeam/provider-pgbeam/apis/v1alpha1"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"time"
)

const (
	errNotDatabase      = "managed resource is not a Database"
	errDatabaseCreate   = "cannot create Database"
	errDatabaseUpdate   = "cannot update Database"
	errDatabaseDelete   = "cannot delete Database"
	errDatabaseObserve  = "cannot observe Database"
	errDatabasePassword = "cannot read database password"
)

func SetupDatabase(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.DatabaseGroupKind)
	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		For(&v1alpha1.Database{}).
		WithOptions(o.ForControllerRuntime()).
		Complete(managed.NewReconciler(mgr,
			resource.ManagedKind(v1alpha1.DatabaseGroupVersionKind),
			managed.WithExternalConnecter(&databaseConnecter{
				connector: connector{
					kube:  mgr.GetClient(),
					usage: resource.NewProviderConfigUsageTracker(mgr.GetClient(), &v1alpha1.ProviderConfigUsage{}),
				},
			}),
			managed.WithLogger(o.Logger.WithValues("controller", name)),
			managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))),
		))
}

type databaseConnecter struct{ connector }

func (c *databaseConnecter) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cl, err := c.getClient(ctx, mg)
	if err != nil {
		return nil, err
	}
	return &databaseExternal{client: cl, kube: c.kube, connector: &c.connector}, nil
}

type databaseExternal struct {
	client    *pgbeam.Client
	kube      client.Client
	connector *connector
}

func (e *databaseExternal) Disconnect(_ context.Context) error { return nil }

func (e *databaseExternal) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.Database)
	if !ok {
		return managed.ExternalObservation{}, fmt.Errorf(errNotDatabase)
	}

	externalName := meta.GetExternalName(cr)
	if externalName == "" {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	database, err := e.client.Databases.GetDatabase(ctx, cr.Spec.ForProvider.ProjectID, externalName)
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, fmt.Errorf("%s: %w", errDatabaseObserve, err)
	}

	cr.Status.AtProvider = databaseObservation(database)
	cr.SetConditions(xpv1.Available())

	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: isDatabaseUpToDate(cr.Spec.ForProvider, database),
	}, nil
}
func (e *databaseExternal) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.Database)
	if !ok {
		return managed.ExternalCreation{}, fmt.Errorf(errNotDatabase)
	}

	fp := cr.Spec.ForProvider
	password, err := e.connector.getSecretValue(ctx, fp.PasswordSecretRef)
	if err != nil {
		return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errDatabasePassword, err)
	}

	req := pgbeam.CreateDatabaseRequest{
		Host:     fp.Host,
		Port:     fp.Port,
		Name:     fp.Name,
		Username: fp.Username,
		Password: &password,
	}
	if fp.SSLMode != "" {
		v := pgbeam.SSLMode(fp.SSLMode)
		req.SslMode = &v
	}
	if fp.Role != "" {
		v := pgbeam.DatabaseRole(fp.Role)
		req.Role = &v
	}
	if fp.PoolRegion != nil {
		req.PoolRegion = fp.PoolRegion
	}
	if fp.QueryTimeoutMs != nil {
		req.QueryTimeoutMs = fp.QueryTimeoutMs
	}
	if fp.AutoReadRouting != nil {
		req.AutoReadRouting = fp.AutoReadRouting
	}
	if fp.CacheConfig != nil {
		req.CacheConfig = &pgbeam.CacheConfig{
			Enabled:    fp.CacheConfig.Enabled,
			TtlSeconds: fp.CacheConfig.TTLSeconds,
			MaxEntries: fp.CacheConfig.MaxEntries,
			SwrSeconds: fp.CacheConfig.SWRSeconds,
		}
	}
	if fp.PoolConfig != nil {
		req.PoolConfig = &pgbeam.PoolConfig{
			PoolSize:    fp.PoolConfig.PoolSize,
			MinPoolSize: fp.PoolConfig.MinPoolSize,
			PoolMode:    pgbeam.PoolMode(fp.PoolConfig.PoolMode),
			MaxActive:   fp.PoolConfig.MaxActive,
		}
	}

	database, err := e.client.Databases.CreateDatabase(ctx, fp.ProjectID, req)
	if err != nil {
		return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errDatabaseCreate, err)
	}

	meta.SetExternalName(cr, database.Id)
	cr.Status.AtProvider = databaseObservation(database)

	connDetails := managed.ConnectionDetails{}
	if database.ConnectionString != nil {
		connDetails["connectionString"] = []byte(*database.ConnectionString)
	}
	return managed.ExternalCreation{ConnectionDetails: connDetails}, nil
}
func (e *databaseExternal) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*v1alpha1.Database)
	if !ok {
		return managed.ExternalUpdate{}, fmt.Errorf(errNotDatabase)
	}

	fp := cr.Spec.ForProvider
	externalName := meta.GetExternalName(cr)

	database, err := e.client.Databases.GetDatabase(ctx, cr.Spec.ForProvider.ProjectID, externalName)
	if err != nil {
		return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errDatabaseObserve, err)
	}

	req := pgbeam.UpdateDatabaseRequest{}
	needsUpdate := false

	if fp.Host != database.Host {
		req.Host = &fp.Host
		needsUpdate = true
	}
	if fp.Port != database.Port {
		req.Port = &fp.Port
		needsUpdate = true
	}
	if fp.Name != database.Name {
		req.Name = &fp.Name
		needsUpdate = true
	}
	if fp.Username != database.Username {
		req.Username = &fp.Username
		needsUpdate = true
	}
	if fp.SSLMode != string(database.SslMode) {
		v := pgbeam.SSLMode(fp.SSLMode)
		req.SslMode = &v
		needsUpdate = true
	}
	if fp.Role != "" {
		v := pgbeam.DatabaseRole(fp.Role)
		if database.Role == nil || v != *database.Role {
			req.Role = &v
			needsUpdate = true
		}
	}
	if fp.PoolRegion != nil && (database.PoolRegion == nil || *fp.PoolRegion != *database.PoolRegion) {
		req.PoolRegion = fp.PoolRegion
		needsUpdate = true
	}
	if fp.QueryTimeoutMs != nil && (database.QueryTimeoutMs == nil || *fp.QueryTimeoutMs != *database.QueryTimeoutMs) {
		req.QueryTimeoutMs = fp.QueryTimeoutMs
		needsUpdate = true
	}
	if fp.AutoReadRouting != nil && (database.AutoReadRouting == nil || *fp.AutoReadRouting != *database.AutoReadRouting) {
		req.AutoReadRouting = fp.AutoReadRouting
		needsUpdate = true
	}
	if fp.CacheConfig != nil {
		req.CacheConfig = &pgbeam.CacheConfig{
			Enabled:    fp.CacheConfig.Enabled,
			TtlSeconds: fp.CacheConfig.TTLSeconds,
			MaxEntries: fp.CacheConfig.MaxEntries,
			SwrSeconds: fp.CacheConfig.SWRSeconds,
		}
		needsUpdate = true
	}
	if fp.PoolConfig != nil {
		req.PoolConfig = &pgbeam.PoolConfig{
			PoolSize:    fp.PoolConfig.PoolSize,
			MinPoolSize: fp.PoolConfig.MinPoolSize,
			PoolMode:    pgbeam.PoolMode(fp.PoolConfig.PoolMode),
			MaxActive:   fp.PoolConfig.MaxActive,
		}
		needsUpdate = true
	}

	password, err := e.connector.getSecretValue(ctx, fp.PasswordSecretRef)
	if err != nil {
		return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errDatabasePassword, err)
	}
	req.Password = &password
	needsUpdate = true

	if needsUpdate {
		if _, err := e.client.Databases.UpdateDatabase(ctx, fp.ProjectID, externalName, req); err != nil {
			return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errDatabaseUpdate, err)
		}
	}
	return managed.ExternalUpdate{}, nil
}
func (e *databaseExternal) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*v1alpha1.Database)
	if !ok {
		return managed.ExternalDelete{}, fmt.Errorf(errNotDatabase)
	}
	if err := e.client.Databases.DeleteDatabase(ctx, cr.Spec.ForProvider.ProjectID, meta.GetExternalName(cr)); err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalDelete{}, nil
		}
		return managed.ExternalDelete{}, fmt.Errorf("%s: %w", errDatabaseDelete, err)
	}
	return managed.ExternalDelete{}, nil
}
func databaseObservation(d *pgbeam.Database) v1alpha1.DatabaseAtProvider {
	obs := v1alpha1.DatabaseAtProvider{
		ID:        d.Id,
		CreatedAt: d.CreatedAt.Format(time.RFC3339),
		UpdatedAt: d.UpdatedAt.Format(time.RFC3339),
	}
	if d.ConnectionString != nil {
		obs.ConnectionString = *d.ConnectionString
	}
	return obs
}
func isDatabaseUpToDate(fp v1alpha1.DatabaseForProvider, d *pgbeam.Database) bool {
	if fp.Host != d.Host {
		return false
	}
	if fp.Port != d.Port {
		return false
	}
	if fp.Name != d.Name {
		return false
	}
	if fp.Username != d.Username {
		return false
	}
	if fp.SSLMode != "" {
		if pgbeam.SSLMode(fp.SSLMode) != d.SslMode {
			return false
		}
	}
	if fp.Role != "" {
		v := pgbeam.DatabaseRole(fp.Role)
		if d.Role == nil || v != *d.Role {
			return false
		}
	}
	if fp.PoolRegion != nil && (d.PoolRegion == nil || *fp.PoolRegion != *d.PoolRegion) {
		return false
	}
	if fp.QueryTimeoutMs != nil && (d.QueryTimeoutMs == nil || *fp.QueryTimeoutMs != *d.QueryTimeoutMs) {
		return false
	}
	if fp.AutoReadRouting != nil && (d.AutoReadRouting == nil || *fp.AutoReadRouting != *d.AutoReadRouting) {
		return false
	}
	if fp.CacheConfig != nil {
		if fp.CacheConfig.Enabled != d.CacheConfig.Enabled {
			return false
		}
		if fp.CacheConfig.TTLSeconds != d.CacheConfig.TtlSeconds {
			return false
		}
		if fp.CacheConfig.MaxEntries != d.CacheConfig.MaxEntries {
			return false
		}
		if fp.CacheConfig.SWRSeconds != d.CacheConfig.SwrSeconds {
			return false
		}
	}
	if fp.PoolConfig != nil {
		if fp.PoolConfig.PoolSize != d.PoolConfig.PoolSize {
			return false
		}
		if fp.PoolConfig.MinPoolSize != d.PoolConfig.MinPoolSize {
			return false
		}
		if pgbeam.PoolMode(fp.PoolConfig.PoolMode) != d.PoolConfig.PoolMode {
			return false
		}
		if d.PoolConfig.MaxActive == nil || *fp.PoolConfig.MaxActive != *d.PoolConfig.MaxActive {
			return false
		}
	}
	return true
}
