// Code generated by generate-crossplane.ts — DO NOT EDIT.

package controller

import (
	"context"
	"fmt"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/controller"
	"github.com/crossplane/crossplane-runtime/pkg/event"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/pkg/resource"
	"github.com/pgbeam/provider-pgbeam/apis/v1alpha1"
	pgbeam "go.pgbeam.com/sdk"
	ctrl "sigs.k8s.io/controller-runtime"
	"time"
)

const (
	errNotHoneytoken     = "managed resource is not a Honeytoken"
	errHoneytokenCreate  = "cannot create Honeytoken"
	errHoneytokenUpdate  = "cannot update Honeytoken"
	errHoneytokenDelete  = "cannot delete Honeytoken"
	errHoneytokenObserve = "cannot observe Honeytoken"
)

func SetupHoneytoken(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.HoneytokenGroupKind)
	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		For(&v1alpha1.Honeytoken{}).
		WithOptions(o.ForControllerRuntime()).
		Complete(managed.NewReconciler(mgr,
			resource.ManagedKind(v1alpha1.HoneytokenGroupVersionKind),
			managed.WithExternalConnecter(&honeytokenConnecter{
				connector: connector{
					kube:  mgr.GetClient(),
					usage: resource.NewProviderConfigUsageTracker(mgr.GetClient(), &v1alpha1.ProviderConfigUsage{}),
				},
			}),
			managed.WithLogger(o.Logger.WithValues("controller", name)),
			managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))),
		))
}

type honeytokenConnecter struct{ connector }

func (c *honeytokenConnecter) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cl, err := c.getClient(ctx, mg)
	if err != nil {
		return nil, err
	}
	return &honeytokenExternal{client: cl}, nil
}

type honeytokenExternal struct{ client *pgbeam.Client }

func (e *honeytokenExternal) Disconnect(_ context.Context) error { return nil }

func (e *honeytokenExternal) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.Honeytoken)
	if !ok {
		return managed.ExternalObservation{}, fmt.Errorf(errNotHoneytoken)
	}

	externalName := meta.GetExternalName(cr)
	if externalName == "" {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	honeytoken, err := e.client.Honeytokens.GetHoneytoken(ctx, cr.Spec.ForProvider.ProjectID, externalName)
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, fmt.Errorf("%s: %w", errHoneytokenObserve, err)
	}

	cr.Status.AtProvider = honeytokenObservation(honeytoken)
	cr.SetConditions(xpv1.Available())

	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: isHoneytokenUpToDate(cr.Spec.ForProvider, honeytoken),
	}, nil
}
func (e *honeytokenExternal) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.Honeytoken)
	if !ok {
		return managed.ExternalCreation{}, fmt.Errorf(errNotHoneytoken)
	}

	fp := cr.Spec.ForProvider
	req := pgbeam.HoneytokenInput{
		RelationName: fp.RelationName,
		Action:       pgbeam.HoneytokenInputAction(fp.Action),
	}
	if fp.SchemaName != nil {
		req.SchemaName = fp.SchemaName
	}

	honeytoken, err := e.client.Honeytokens.CreateHoneytoken(ctx, fp.ProjectID, req)
	if err != nil {
		return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errHoneytokenCreate, err)
	}

	meta.SetExternalName(cr, honeytoken.Id)
	cr.Status.AtProvider = honeytokenObservation(honeytoken)
	return managed.ExternalCreation{}, nil
}
func (e *honeytokenExternal) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*v1alpha1.Honeytoken)
	if !ok {
		return managed.ExternalUpdate{}, fmt.Errorf(errNotHoneytoken)
	}

	fp := cr.Spec.ForProvider
	externalName := meta.GetExternalName(cr)

	honeytoken, err := e.client.Honeytokens.GetHoneytoken(ctx, cr.Spec.ForProvider.ProjectID, externalName)
	if err != nil {
		return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errHoneytokenObserve, err)
	}

	req := pgbeam.HoneytokenInput{}
	needsUpdate := !isHoneytokenUpToDate(fp, honeytoken)

	if fp.SchemaName != nil {
		req.SchemaName = fp.SchemaName
	}
	req.RelationName = fp.RelationName
	if fp.Action != "" {
		v := pgbeam.HoneytokenInputAction(fp.Action)
		req.Action = v
	}

	if needsUpdate {
		if _, err := e.client.Honeytokens.UpdateHoneytoken(ctx, fp.ProjectID, externalName, req); err != nil {
			return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errHoneytokenUpdate, err)
		}
	}
	return managed.ExternalUpdate{}, nil
}
func (e *honeytokenExternal) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*v1alpha1.Honeytoken)
	if !ok {
		return managed.ExternalDelete{}, fmt.Errorf(errNotHoneytoken)
	}
	if err := e.client.Honeytokens.DeleteHoneytoken(ctx, cr.Spec.ForProvider.ProjectID, meta.GetExternalName(cr)); err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalDelete{}, nil
		}
		return managed.ExternalDelete{}, fmt.Errorf("%s: %w", errHoneytokenDelete, err)
	}
	return managed.ExternalDelete{}, nil
}
func honeytokenObservation(h *pgbeam.Honeytoken) v1alpha1.HoneytokenAtProvider {
	obs := v1alpha1.HoneytokenAtProvider{
		ID:        h.Id,
		CreatedAt: h.CreatedAt.Format(time.RFC3339),
		UpdatedAt: h.UpdatedAt.Format(time.RFC3339),
	}
	return obs
}
func isHoneytokenUpToDate(fp v1alpha1.HoneytokenForProvider, h *pgbeam.Honeytoken) bool {
	if fp.SchemaName != nil && (h.SchemaName == nil || *fp.SchemaName != *h.SchemaName) {
		return false
	}
	if fp.RelationName != h.RelationName {
		return false
	}
	if fp.Action != string(h.Action) {
		return false
	}
	return true
}
