// Code generated by generate-crossplane.ts — DO NOT EDIT.

package controller

import (
	"context"
	"fmt"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/controller"
	"github.com/crossplane/crossplane-runtime/pkg/event"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/pkg/resource"
	"github.com/pgbeam/provider-pgbeam/apis/v1alpha1"
	pgbeam "go.pgbeam.com/sdk"
	"reflect"
	ctrl "sigs.k8s.io/controller-runtime"
	"time"
)

const (
	errNotPolicyProfile     = "managed resource is not a PolicyProfile"
	errPolicyProfileCreate  = "cannot create PolicyProfile"
	errPolicyProfileUpdate  = "cannot update PolicyProfile"
	errPolicyProfileDelete  = "cannot delete PolicyProfile"
	errPolicyProfileObserve = "cannot observe PolicyProfile"
)

func SetupPolicyProfile(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.PolicyProfileGroupKind)
	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		For(&v1alpha1.PolicyProfile{}).
		WithOptions(o.ForControllerRuntime()).
		Complete(managed.NewReconciler(mgr,
			resource.ManagedKind(v1alpha1.PolicyProfileGroupVersionKind),
			managed.WithExternalConnecter(&policyProfileConnecter{
				connector: connector{
					kube:  mgr.GetClient(),
					usage: resource.NewProviderConfigUsageTracker(mgr.GetClient(), &v1alpha1.ProviderConfigUsage{}),
				},
			}),
			managed.WithLogger(o.Logger.WithValues("controller", name)),
			managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))),
		))
}

type policyProfileConnecter struct{ connector }

func (c *policyProfileConnecter) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cl, err := c.getClient(ctx, mg)
	if err != nil {
		return nil, err
	}
	return &policyProfileExternal{client: cl}, nil
}

type policyProfileExternal struct{ client *pgbeam.Client }

func (e *policyProfileExternal) Disconnect(_ context.Context) error { return nil }

func (e *policyProfileExternal) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.PolicyProfile)
	if !ok {
		return managed.ExternalObservation{}, fmt.Errorf(errNotPolicyProfile)
	}

	externalName := meta.GetExternalName(cr)
	if externalName == "" {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	policyProfile, err := e.client.Policies.GetPolicyProfile(ctx, cr.Spec.ForProvider.ProjectID, externalName)
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, fmt.Errorf("%s: %w", errPolicyProfileObserve, err)
	}

	cr.Status.AtProvider = policyProfileObservation(policyProfile)
	cr.SetConditions(xpv1.Available())

	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: isPolicyProfileUpToDate(cr.Spec.ForProvider, policyProfile),
	}, nil
}
func (e *policyProfileExternal) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.PolicyProfile)
	if !ok {
		return managed.ExternalCreation{}, fmt.Errorf(errNotPolicyProfile)
	}

	fp := cr.Spec.ForProvider
	req := pgbeam.PolicyProfileInput{
		Name: fp.Name,
	}
	if fp.AccessMode != "" {
		v := pgbeam.PolicyProfileInputAccessMode(fp.AccessMode)
		req.AccessMode = &v
	}
	if fp.TableAllowlist != nil {
		req.TableAllowlist = &fp.TableAllowlist
	}
	if fp.TableDenylist != nil {
		req.TableDenylist = &fp.TableDenylist
	}
	if fp.MaskingRules != nil {
		maskingRulesEntries := make([]pgbeam.MaskingRule, len(fp.MaskingRules))
		for i, s := range fp.MaskingRules {
			maskingRulesEntries[i] = pgbeam.MaskingRule{
				Table:  s.Table,
				Column: s.Column,
				Kind:   pgbeam.MaskingRuleKind(s.Kind),
			}
		}
		req.MaskingRules = &maskingRulesEntries
	}
	if fp.BudgetQueriesPerHour != nil {
		req.BudgetQueriesPerHour = fp.BudgetQueriesPerHour
	}
	if fp.BudgetQueriesPerDay != nil {
		req.BudgetQueriesPerDay = fp.BudgetQueriesPerDay
	}
	if fp.MaxRows != nil {
		req.MaxRows = fp.MaxRows
	}
	if fp.StatementTimeoutMs != nil {
		req.StatementTimeoutMs = fp.StatementTimeoutMs
	}
	if fp.RowFilters != nil {
		rowFiltersEntries := make([]pgbeam.RowFilter, len(fp.RowFilters))
		for i, s := range fp.RowFilters {
			rowFiltersEntries[i] = pgbeam.RowFilter{
				Table:     s.Table,
				Predicate: s.Predicate,
			}
		}
		req.RowFilters = &rowFiltersEntries
	}
	if fp.WriteMode != "" {
		v := pgbeam.PolicyProfileInputWriteMode(fp.WriteMode)
		req.WriteMode = &v
	}
	if fp.ApprovalMode != "" {
		v := pgbeam.PolicyProfileInputApprovalMode(fp.ApprovalMode)
		req.ApprovalMode = &v
	}
	if fp.ApprovalAutoMaxRows != nil {
		req.ApprovalAutoMaxRows = fp.ApprovalAutoMaxRows
	}
	if fp.ApprovalTimeoutSeconds != nil {
		req.ApprovalTimeoutSeconds = fp.ApprovalTimeoutSeconds
	}
	if fp.MigrationSafety != "" {
		v := pgbeam.PolicyProfileInputMigrationSafety(fp.MigrationSafety)
		req.MigrationSafety = &v
	}
	if fp.EgressBytesPerDay != nil {
		req.EgressBytesPerDay = fp.EgressBytesPerDay
	}
	if fp.MaxAffectedRows != nil {
		req.MaxAffectedRows = fp.MaxAffectedRows
	}
	if fp.StatementRules != nil {
		req.StatementRules = &pgbeam.StatementRules{
			Allow: fp.StatementRules.Allow,
			Deny:  fp.StatementRules.Deny,
		}
	}

	policyProfile, err := e.client.Policies.CreatePolicyProfile(ctx, fp.ProjectID, req)
	if err != nil {
		return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errPolicyProfileCreate, err)
	}

	meta.SetExternalName(cr, policyProfile.Id)
	cr.Status.AtProvider = policyProfileObservation(policyProfile)
	return managed.ExternalCreation{}, nil
}
func (e *policyProfileExternal) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*v1alpha1.PolicyProfile)
	if !ok {
		return managed.ExternalUpdate{}, fmt.Errorf(errNotPolicyProfile)
	}

	fp := cr.Spec.ForProvider
	externalName := meta.GetExternalName(cr)

	policyProfile, err := e.client.Policies.GetPolicyProfile(ctx, cr.Spec.ForProvider.ProjectID, externalName)
	if err != nil {
		return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errPolicyProfileObserve, err)
	}

	req := pgbeam.PolicyProfileInput{}
	needsUpdate := !isPolicyProfileUpToDate(fp, policyProfile)

	req.Name = fp.Name
	if fp.AccessMode != "" {
		v := pgbeam.PolicyProfileInputAccessMode(fp.AccessMode)
		req.AccessMode = &v
	}
	if fp.TableAllowlist != nil {
		req.TableAllowlist = &fp.TableAllowlist
	}
	if fp.TableDenylist != nil {
		req.TableDenylist = &fp.TableDenylist
	}
	if fp.MaskingRules != nil {
		maskingRulesEntries := make([]pgbeam.MaskingRule, len(fp.MaskingRules))
		for i, s := range fp.MaskingRules {
			maskingRulesEntries[i] = pgbeam.MaskingRule{
				Table:  s.Table,
				Column: s.Column,
				Kind:   pgbeam.MaskingRuleKind(s.Kind),
			}
		}
		req.MaskingRules = &maskingRulesEntries
	}
	if fp.BudgetQueriesPerHour != nil {
		req.BudgetQueriesPerHour = fp.BudgetQueriesPerHour
	}
	if fp.BudgetQueriesPerDay != nil {
		req.BudgetQueriesPerDay = fp.BudgetQueriesPerDay
	}
	if fp.MaxRows != nil {
		req.MaxRows = fp.MaxRows
	}
	if fp.StatementTimeoutMs != nil {
		req.StatementTimeoutMs = fp.StatementTimeoutMs
	}
	if fp.RowFilters != nil {
		rowFiltersEntries := make([]pgbeam.RowFilter, len(fp.RowFilters))
		for i, s := range fp.RowFilters {
			rowFiltersEntries[i] = pgbeam.RowFilter{
				Table:     s.Table,
				Predicate: s.Predicate,
			}
		}
		req.RowFilters = &rowFiltersEntries
	}
	if fp.WriteMode != "" {
		v := pgbeam.PolicyProfileInputWriteMode(fp.WriteMode)
		req.WriteMode = &v
	}
	if fp.ApprovalMode != "" {
		v := pgbeam.PolicyProfileInputApprovalMode(fp.ApprovalMode)
		req.ApprovalMode = &v
	}
	if fp.ApprovalAutoMaxRows != nil {
		req.ApprovalAutoMaxRows = fp.ApprovalAutoMaxRows
	}
	if fp.ApprovalTimeoutSeconds != nil {
		req.ApprovalTimeoutSeconds = fp.ApprovalTimeoutSeconds
	}
	if fp.MigrationSafety != "" {
		v := pgbeam.PolicyProfileInputMigrationSafety(fp.MigrationSafety)
		req.MigrationSafety = &v
	}
	if fp.EgressBytesPerDay != nil {
		req.EgressBytesPerDay = fp.EgressBytesPerDay
	}
	if fp.MaxAffectedRows != nil {
		req.MaxAffectedRows = fp.MaxAffectedRows
	}
	if fp.StatementRules != nil {
		req.StatementRules = &pgbeam.StatementRules{
			Allow: fp.StatementRules.Allow,
			Deny:  fp.StatementRules.Deny,
		}
	}

	if needsUpdate {
		if _, err := e.client.Policies.UpdatePolicyProfile(ctx, fp.ProjectID, externalName, req); err != nil {
			return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errPolicyProfileUpdate, err)
		}
	}
	return managed.ExternalUpdate{}, nil
}
func (e *policyProfileExternal) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*v1alpha1.PolicyProfile)
	if !ok {
		return managed.ExternalDelete{}, fmt.Errorf(errNotPolicyProfile)
	}
	if err := e.client.Policies.DeletePolicyProfile(ctx, cr.Spec.ForProvider.ProjectID, meta.GetExternalName(cr)); err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalDelete{}, nil
		}
		return managed.ExternalDelete{}, fmt.Errorf("%s: %w", errPolicyProfileDelete, err)
	}
	return managed.ExternalDelete{}, nil
}
func policyProfileObservation(p *pgbeam.PolicyProfile) v1alpha1.PolicyProfileAtProvider {
	obs := v1alpha1.PolicyProfileAtProvider{
		ID:        p.Id,
		CreatedAt: p.CreatedAt.Format(time.RFC3339),
		UpdatedAt: p.UpdatedAt.Format(time.RFC3339),
	}
	return obs
}
func isPolicyProfileUpToDate(fp v1alpha1.PolicyProfileForProvider, p *pgbeam.PolicyProfile) bool {
	if fp.Name != p.Name {
		return false
	}
	if fp.AccessMode != "" {
		if fp.AccessMode != string(p.AccessMode) {
			return false
		}
	}
	if fp.TableAllowlist != nil {
		pTags := p.TableAllowlist
		if len(fp.TableAllowlist) != len(pTags) {
			return false
		}
		for i, t := range fp.TableAllowlist {
			if t != (pTags)[i] {
				return false
			}
		}
	}
	if fp.TableDenylist != nil {
		pTags := p.TableDenylist
		if len(fp.TableDenylist) != len(pTags) {
			return false
		}
		for i, t := range fp.TableDenylist {
			if t != (pTags)[i] {
				return false
			}
		}
	}
	if fp.MaskingRules != nil {
		pMaskingRules := p.MaskingRules
		if len(fp.MaskingRules) != len(pMaskingRules) {
			return false
		}
		for i := range fp.MaskingRules {
			if fp.MaskingRules[i].Table != (pMaskingRules)[i].Table {
				return false
			}
			if fp.MaskingRules[i].Column != (pMaskingRules)[i].Column {
				return false
			}
			if fp.MaskingRules[i].Kind != string((pMaskingRules)[i].Kind) {
				return false
			}
		}
	}
	if fp.BudgetQueriesPerHour != nil && (p.BudgetQueriesPerHour == nil || *fp.BudgetQueriesPerHour != *p.BudgetQueriesPerHour) {
		return false
	}
	if fp.BudgetQueriesPerDay != nil && (p.BudgetQueriesPerDay == nil || *fp.BudgetQueriesPerDay != *p.BudgetQueriesPerDay) {
		return false
	}
	if fp.MaxRows != nil && (p.MaxRows == nil || *fp.MaxRows != *p.MaxRows) {
		return false
	}
	if fp.StatementTimeoutMs != nil && (p.StatementTimeoutMs == nil || *fp.StatementTimeoutMs != *p.StatementTimeoutMs) {
		return false
	}
	if fp.RowFilters != nil {
		pRowFilters := p.RowFilters
		if pRowFilters == nil {
			if len(fp.RowFilters) != 0 {
				return false
			}
		} else if len(fp.RowFilters) != len(*pRowFilters) {
			return false
		} else {
			for i := range fp.RowFilters {
				if fp.RowFilters[i].Table != (*pRowFilters)[i].Table {
					return false
				}
				if fp.RowFilters[i].Predicate != (*pRowFilters)[i].Predicate {
					return false
				}
			}
		}
	}
	if fp.WriteMode != "" {
		v := pgbeam.PolicyProfileWriteMode(fp.WriteMode)
		if p.WriteMode == nil || string(v) != string(*p.WriteMode) {
			return false
		}
	}
	if fp.ApprovalMode != "" {
		v := pgbeam.PolicyProfileApprovalMode(fp.ApprovalMode)
		if p.ApprovalMode == nil || string(v) != string(*p.ApprovalMode) {
			return false
		}
	}
	if fp.ApprovalAutoMaxRows != nil && (p.ApprovalAutoMaxRows == nil || *fp.ApprovalAutoMaxRows != *p.ApprovalAutoMaxRows) {
		return false
	}
	if fp.ApprovalTimeoutSeconds != nil && (p.ApprovalTimeoutSeconds == nil || *fp.ApprovalTimeoutSeconds != *p.ApprovalTimeoutSeconds) {
		return false
	}
	if fp.MigrationSafety != "" {
		v := pgbeam.PolicyProfileMigrationSafety(fp.MigrationSafety)
		if p.MigrationSafety == nil || string(v) != string(*p.MigrationSafety) {
			return false
		}
	}
	if fp.EgressBytesPerDay != nil && (p.EgressBytesPerDay == nil || *fp.EgressBytesPerDay != *p.EgressBytesPerDay) {
		return false
	}
	if fp.MaxAffectedRows != nil && (p.MaxAffectedRows == nil || *fp.MaxAffectedRows != *p.MaxAffectedRows) {
		return false
	}
	if fp.StatementRules != nil {
		if !reflect.DeepEqual(fp.StatementRules.Allow, p.StatementRules.Allow) {
			return false
		}
		if !reflect.DeepEqual(fp.StatementRules.Deny, p.StatementRules.Deny) {
			return false
		}
	}
	return true
}
