// Code generated by generate-crossplane.ts — DO NOT EDIT.

package controller

import (
	"context"
	"fmt"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/controller"
	"github.com/crossplane/crossplane-runtime/pkg/event"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/pkg/resource"
	pgbeam "github.com/pgbeam/pgbeam-go"
	"github.com/pgbeam/provider-pgbeam/apis/v1alpha1"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"time"
)

const (
	errNotProject      = "managed resource is not a Project"
	errProjectCreate   = "cannot create Project"
	errProjectUpdate   = "cannot update Project"
	errProjectDelete   = "cannot delete Project"
	errProjectObserve  = "cannot observe Project"
	errProjectPassword = "cannot read database password"
)

func SetupProject(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.ProjectGroupKind)
	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		For(&v1alpha1.Project{}).
		WithOptions(o.ForControllerRuntime()).
		Complete(managed.NewReconciler(mgr,
			resource.ManagedKind(v1alpha1.ProjectGroupVersionKind),
			managed.WithExternalConnecter(&projectConnecter{
				connector: connector{
					kube:  mgr.GetClient(),
					usage: resource.NewProviderConfigUsageTracker(mgr.GetClient(), &v1alpha1.ProviderConfigUsage{}),
				},
			}),
			managed.WithLogger(o.Logger.WithValues("controller", name)),
			managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))),
		))
}

type projectConnecter struct{ connector }

func (c *projectConnecter) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cl, err := c.getClient(ctx, mg)
	if err != nil {
		return nil, err
	}
	return &projectExternal{client: cl, kube: c.kube, connector: &c.connector}, nil
}

type projectExternal struct {
	client    *pgbeam.Client
	kube      client.Client
	connector *connector
}

func (e *projectExternal) Disconnect(_ context.Context) error { return nil }

func (e *projectExternal) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.Project)
	if !ok {
		return managed.ExternalObservation{}, fmt.Errorf(errNotProject)
	}

	externalName := meta.GetExternalName(cr)
	if externalName == "" {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	project, err := e.client.Projects.GetProject(ctx, externalName)
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, fmt.Errorf("%s: %w", errProjectObserve, err)
	}

	cr.Status.AtProvider = projectObservation(project)
	cr.SetConditions(xpv1.Available())

	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: isProjectUpToDate(cr.Spec.ForProvider, project),
	}, nil
}
func (e *projectExternal) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.Project)
	if !ok {
		return managed.ExternalCreation{}, fmt.Errorf(errNotProject)
	}

	fp := cr.Spec.ForProvider
	password, err := e.connector.getSecretValue(ctx, fp.Database.PasswordSecretRef)
	if err != nil {
		return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errProjectPassword, err)
	}

	databaseReq := pgbeam.CreateDatabaseRequest{
		Host:     fp.Database.Host,
		Port:     fp.Database.Port,
		Name:     fp.Database.Name,
		Username: fp.Database.Username,
		Password: &password,
	}
	if fp.Database.SSLMode != nil {
		v := pgbeam.SSLMode(*fp.Database.SSLMode)
		databaseReq.SslMode = &v
	}
	if fp.Database.Role != nil {
		v := pgbeam.DatabaseRole(*fp.Database.Role)
		databaseReq.Role = &v
	}
	if fp.Database.PoolRegion != nil {
		databaseReq.PoolRegion = fp.Database.PoolRegion
	}
	if fp.Database.QueryTimeoutMs != nil {
		databaseReq.QueryTimeoutMs = fp.Database.QueryTimeoutMs
	}
	if fp.Database.AutoReadRouting != nil {
		databaseReq.AutoReadRouting = fp.Database.AutoReadRouting
	}
	if fp.Database.CacheConfig != nil {
		databaseReq.CacheConfig = &pgbeam.CacheConfig{
			Enabled:    fp.Database.CacheConfig.Enabled,
			TtlSeconds: fp.Database.CacheConfig.TTLSeconds,
			MaxEntries: fp.Database.CacheConfig.MaxEntries,
			SwrSeconds: fp.Database.CacheConfig.SWRSeconds,
		}
	}
	if fp.Database.PoolConfig != nil {
		databaseReq.PoolConfig = &pgbeam.PoolConfig{
			PoolSize:    fp.Database.PoolConfig.PoolSize,
			MinPoolSize: fp.Database.PoolConfig.MinPoolSize,
			PoolMode:    pgbeam.PoolMode(fp.Database.PoolConfig.PoolMode),
			MaxActive:   fp.Database.PoolConfig.MaxActive,
		}
	}

	req := pgbeam.CreateProjectRequest{
		OrgId:    fp.OrgID,
		Name:     fp.Name,
		Database: databaseReq,
	}
	if fp.Description != nil {
		req.Description = fp.Description
	}
	if fp.Tags != nil {
		req.Tags = &fp.Tags
	}
	if fp.Cloud != "" {
		v := pgbeam.CreateProjectRequestCloud(fp.Cloud)
		req.Cloud = &v
	}
	if fp.Database.PoolRegion != nil {
		req.Database.PoolRegion = fp.Database.PoolRegion
	}
	if fp.Database.QueryTimeoutMs != nil {
		req.Database.QueryTimeoutMs = fp.Database.QueryTimeoutMs
	}
	if fp.Database.AutoReadRouting != nil {
		req.Database.AutoReadRouting = fp.Database.AutoReadRouting
	}
	if fp.Database.CacheConfig != nil {
		req.Database.CacheConfig = &pgbeam.CacheConfig{
			Enabled:    fp.Database.CacheConfig.Enabled,
			TtlSeconds: fp.Database.CacheConfig.TTLSeconds,
			MaxEntries: fp.Database.CacheConfig.MaxEntries,
			SwrSeconds: fp.Database.CacheConfig.SWRSeconds,
		}
	}
	if fp.Database.PoolConfig != nil {
		req.Database.PoolConfig = &pgbeam.PoolConfig{
			PoolSize:    fp.Database.PoolConfig.PoolSize,
			MinPoolSize: fp.Database.PoolConfig.MinPoolSize,
			PoolMode:    pgbeam.PoolMode(fp.Database.PoolConfig.PoolMode),
			MaxActive:   fp.Database.PoolConfig.MaxActive,
		}
	}

	resp, err := e.client.Projects.CreateProject(ctx, req)
	if err != nil {
		return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errProjectCreate, err)
	}

	// Rate-limit fields are not supported in CreateProjectRequest.
	// If specified, issue an immediate update after creation.
	updateReq := pgbeam.UpdateProjectRequest{}
	needsPostCreateUpdate := false
	if fp.QueriesPerSecond != nil {
		updateReq.QueriesPerSecond = fp.QueriesPerSecond
		needsPostCreateUpdate = true
	}
	if fp.BurstSize != nil {
		updateReq.BurstSize = fp.BurstSize
		needsPostCreateUpdate = true
	}
	if fp.MaxConnections != nil {
		updateReq.MaxConnections = fp.MaxConnections
		needsPostCreateUpdate = true
	}
	if fp.AllowedCidrs != nil {
		updateReq.AllowedCidrs = &fp.AllowedCidrs
		needsPostCreateUpdate = true
	}
	if fp.Status != "" {
		v := pgbeam.ProjectStatus(fp.Status)
		updateReq.Status = &v
		needsPostCreateUpdate = true
	}
	if needsPostCreateUpdate {
		updated, err := e.client.Projects.UpdateProject(ctx, resp.Project.Id, updateReq)
		if err != nil {
			return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errProjectUpdate, err)
		}
		resp.Project = *updated
	}

	meta.SetExternalName(cr, resp.Project.Id)
	cr.Status.AtProvider = projectObservation(&resp.Project)
	if resp.Database != nil {
		cr.Status.AtProvider.PrimaryDatabaseID = resp.Database.Id
	}

	connDetails := managed.ConnectionDetails{}
	if resp.Project.ProxyHost != nil && *resp.Project.ProxyHost != "" {
		connDetails["proxyHost"] = []byte(*resp.Project.ProxyHost)
	}
	return managed.ExternalCreation{ConnectionDetails: connDetails}, nil
}
func (e *projectExternal) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*v1alpha1.Project)
	if !ok {
		return managed.ExternalUpdate{}, fmt.Errorf(errNotProject)
	}

	fp := cr.Spec.ForProvider
	externalName := meta.GetExternalName(cr)

	project, err := e.client.Projects.GetProject(ctx, externalName)
	if err != nil {
		return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errProjectObserve, err)
	}

	req := pgbeam.UpdateProjectRequest{}
	needsUpdate := false

	if fp.Name != project.Name {
		req.Name = &fp.Name
		needsUpdate = true
	}
	if fp.Description != nil && (project.Description == nil || *fp.Description != *project.Description) {
		req.Description = fp.Description
		needsUpdate = true
	}
	if fp.Tags != nil {
		req.Tags = &fp.Tags
		needsUpdate = true
	}
	if fp.QueriesPerSecond != nil && (project.QueriesPerSecond == nil || *fp.QueriesPerSecond != *project.QueriesPerSecond) {
		req.QueriesPerSecond = fp.QueriesPerSecond
		needsUpdate = true
	}
	if fp.BurstSize != nil && (project.BurstSize == nil || *fp.BurstSize != *project.BurstSize) {
		req.BurstSize = fp.BurstSize
		needsUpdate = true
	}
	if fp.MaxConnections != nil && (project.MaxConnections == nil || *fp.MaxConnections != *project.MaxConnections) {
		req.MaxConnections = fp.MaxConnections
		needsUpdate = true
	}
	if fp.AllowedCidrs != nil {
		req.AllowedCidrs = &fp.AllowedCidrs
		needsUpdate = true
	}
	if fp.Status != "" && pgbeam.ProjectStatus(fp.Status) != project.Status {
		v := pgbeam.ProjectStatus(fp.Status)
		req.Status = &v
		needsUpdate = true
	}

	if needsUpdate {
		if _, err := e.client.Projects.UpdateProject(ctx, externalName, req); err != nil {
			return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errProjectUpdate, err)
		}
	}
	return managed.ExternalUpdate{}, nil
}
func (e *projectExternal) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*v1alpha1.Project)
	if !ok {
		return managed.ExternalDelete{}, fmt.Errorf(errNotProject)
	}
	if err := e.client.Projects.DeleteProject(ctx, meta.GetExternalName(cr)); err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalDelete{}, nil
		}
		return managed.ExternalDelete{}, fmt.Errorf("%s: %w", errProjectDelete, err)
	}
	return managed.ExternalDelete{}, nil
}
func projectObservation(p *pgbeam.Project) v1alpha1.ProjectAtProvider {
	obs := v1alpha1.ProjectAtProvider{
		ID:        p.Id,
		CreatedAt: p.CreatedAt.Format(time.RFC3339),
		UpdatedAt: p.UpdatedAt.Format(time.RFC3339),
	}
	if p.ProxyHost != nil {
		obs.ProxyHost = *p.ProxyHost
	}
	if p.DatabaseCount != nil {
		obs.DatabaseCount = *p.DatabaseCount
	}
	if p.ActiveConnections != nil {
		obs.ActiveConnections = *p.ActiveConnections
	}
	return obs
}
func isProjectUpToDate(fp v1alpha1.ProjectForProvider, p *pgbeam.Project) bool {
	if fp.Name != p.Name {
		return false
	}
	if fp.Description != nil && (p.Description == nil || *fp.Description != *p.Description) {
		return false
	}
	if fp.Tags != nil {
		pTags := p.Tags
		if pTags == nil {
			if len(fp.Tags) != 0 {
				return false
			}
		} else {
			if len(fp.Tags) != len(*pTags) {
				return false
			}
			for i, t := range fp.Tags {
				if t != (*pTags)[i] {
					return false
				}
			}
		}
	}
	if fp.QueriesPerSecond != nil && (p.QueriesPerSecond == nil || *fp.QueriesPerSecond != *p.QueriesPerSecond) {
		return false
	}
	if fp.BurstSize != nil && (p.BurstSize == nil || *fp.BurstSize != *p.BurstSize) {
		return false
	}
	if fp.MaxConnections != nil && (p.MaxConnections == nil || *fp.MaxConnections != *p.MaxConnections) {
		return false
	}
	if fp.AllowedCidrs != nil {
		pSlice := p.AllowedCidrs
		if pSlice == nil {
			if len(fp.AllowedCidrs) != 0 {
				return false
			}
		} else {
			if len(fp.AllowedCidrs) != len(*pSlice) {
				return false
			}
			for i, t := range fp.AllowedCidrs {
				if t != (*pSlice)[i] {
					return false
				}
			}
		}
	}
	if fp.Status != "" {
		if pgbeam.ProjectStatus(fp.Status) != p.Status {
			return false
		}
	}
	return true
}
