// Code generated by generate-crossplane.ts — DO NOT EDIT.

package controller

import (
	"context"
	"fmt"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/controller"
	"github.com/crossplane/crossplane-runtime/pkg/event"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/pkg/resource"
	pgbeam "github.com/pgbeam/pgbeam-go"
	"github.com/pgbeam/provider-pgbeam/apis/v1alpha1"
	ctrl "sigs.k8s.io/controller-runtime"
	"time"
)

const (
	errNotReplica     = "managed resource is not a Replica"
	errReplicaCreate  = "cannot create Replica"
	errReplicaUpdate  = "Replica is fully immutable and cannot be updated; delete and recreate"
	errReplicaDelete  = "cannot delete Replica"
	errReplicaObserve = "cannot observe Replica"
)

func SetupReplica(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.ReplicaGroupKind)
	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		For(&v1alpha1.Replica{}).
		WithOptions(o.ForControllerRuntime()).
		Complete(managed.NewReconciler(mgr,
			resource.ManagedKind(v1alpha1.ReplicaGroupVersionKind),
			managed.WithExternalConnecter(&replicaConnecter{
				connector: connector{
					kube:  mgr.GetClient(),
					usage: resource.NewProviderConfigUsageTracker(mgr.GetClient(), &v1alpha1.ProviderConfigUsage{}),
				},
			}),
			managed.WithLogger(o.Logger.WithValues("controller", name)),
			managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))),
		))
}

type replicaConnecter struct{ connector }

func (c *replicaConnecter) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cl, err := c.getClient(ctx, mg)
	if err != nil {
		return nil, err
	}
	return &replicaExternal{client: cl}, nil
}

type replicaExternal struct{ client *pgbeam.Client }

func (e *replicaExternal) Disconnect(_ context.Context) error { return nil }

func (e *replicaExternal) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.Replica)
	if !ok {
		return managed.ExternalObservation{}, fmt.Errorf(errNotReplica)
	}

	externalName := meta.GetExternalName(cr)
	if externalName == "" {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	// No individual Get endpoint; list and filter by ID.
	replica, err := e.getReplica(ctx, cr.Spec.ForProvider.DatabaseID, externalName)
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, fmt.Errorf("%s: %w", errReplicaObserve, err)
	}

	cr.Status.AtProvider = v1alpha1.ReplicaAtProvider{
		ID:        replica.Id,
		CreatedAt: replica.CreatedAt.Format(time.RFC3339),
		UpdatedAt: replica.UpdatedAt.Format(time.RFC3339),
	}
	cr.SetConditions(xpv1.Available())

	return managed.ExternalObservation{ResourceExists: true, ResourceUpToDate: true}, nil
}
func (e *replicaExternal) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.Replica)
	if !ok {
		return managed.ExternalCreation{}, fmt.Errorf(errNotReplica)
	}

	fp := cr.Spec.ForProvider
	req := pgbeam.CreateReplicaRequest{
		Host: fp.Host,
		Port: fp.Port,
	}
	if fp.SSLMode != "" {
		v := pgbeam.SSLMode(fp.SSLMode)
		req.SslMode = &v
	}

	replica, err := e.client.Projects.CreateReplica(ctx, fp.DatabaseID, req)
	if err != nil {
		return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errReplicaCreate, err)
	}

	meta.SetExternalName(cr, replica.Id)
	cr.Status.AtProvider = v1alpha1.ReplicaAtProvider{
		ID:        replica.Id,
		CreatedAt: replica.CreatedAt.Format(time.RFC3339),
		UpdatedAt: replica.UpdatedAt.Format(time.RFC3339),
	}
	return managed.ExternalCreation{}, nil
}
func (e *replicaExternal) Update(_ context.Context, _ resource.Managed) (managed.ExternalUpdate, error) {
	return managed.ExternalUpdate{}, fmt.Errorf(errReplicaUpdate)
}
func (e *replicaExternal) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*v1alpha1.Replica)
	if !ok {
		return managed.ExternalDelete{}, fmt.Errorf(errNotReplica)
	}
	if err := e.client.Projects.DeleteReplica(ctx, cr.Spec.ForProvider.DatabaseID, meta.GetExternalName(cr)); err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalDelete{}, nil
		}
		return managed.ExternalDelete{}, fmt.Errorf("%s: %w", errReplicaDelete, err)
	}
	return managed.ExternalDelete{}, nil
}

// getReplica lists replicas for a database and returns the one matching id.
func (e *replicaExternal) getReplica(ctx context.Context, databaseID string, id string) (*pgbeam.Replica, error) {
	resp, err := e.client.Projects.ListReplicas(ctx, databaseID)
	if err != nil {
		return nil, err
	}
	for i := range resp.Replicas {
		if resp.Replicas[i].Id == id {
			return &resp.Replicas[i], nil
		}
	}
	return nil, &pgbeam.APIError{StatusCode: 404, Status: "Not Found", Body: fmt.Sprintf("replica %s not found in database %s", id, databaseID)}
}
