// Code generated by generate-crossplane.ts — DO NOT EDIT.

package controller

import (
	"context"
	"fmt"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/controller"
	"github.com/crossplane/crossplane-runtime/pkg/event"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/pkg/resource"
	"github.com/pgbeam/provider-pgbeam/apis/v1alpha1"
	pgbeam "go.pgbeam.com/sdk"
	ctrl "sigs.k8s.io/controller-runtime"
	"time"
)

const (
	errNotSelfHostEnrollment     = "managed resource is not a SelfHostEnrollment"
	errSelfHostEnrollmentCreate  = "cannot create SelfHostEnrollment"
	errSelfHostEnrollmentUpdate  = "SelfHostEnrollment is fully immutable and cannot be updated; delete and recreate"
	errSelfHostEnrollmentDelete  = "cannot delete SelfHostEnrollment"
	errSelfHostEnrollmentObserve = "cannot observe SelfHostEnrollment"
)

func SetupSelfHostEnrollment(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.SelfHostEnrollmentGroupKind)
	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		For(&v1alpha1.SelfHostEnrollment{}).
		WithOptions(o.ForControllerRuntime()).
		Complete(managed.NewReconciler(mgr,
			resource.ManagedKind(v1alpha1.SelfHostEnrollmentGroupVersionKind),
			managed.WithExternalConnecter(&selfHostEnrollmentConnecter{
				connector: connector{
					kube:  mgr.GetClient(),
					usage: resource.NewProviderConfigUsageTracker(mgr.GetClient(), &v1alpha1.ProviderConfigUsage{}),
				},
			}),
			managed.WithLogger(o.Logger.WithValues("controller", name)),
			managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))),
		))
}

type selfHostEnrollmentConnecter struct{ connector }

func (c *selfHostEnrollmentConnecter) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cl, err := c.getClient(ctx, mg)
	if err != nil {
		return nil, err
	}
	return &selfHostEnrollmentExternal{client: cl}, nil
}

type selfHostEnrollmentExternal struct{ client *pgbeam.Client }

func (e *selfHostEnrollmentExternal) Disconnect(_ context.Context) error { return nil }

func (e *selfHostEnrollmentExternal) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.SelfHostEnrollment)
	if !ok {
		return managed.ExternalObservation{}, fmt.Errorf(errNotSelfHostEnrollment)
	}

	externalName := meta.GetExternalName(cr)
	if externalName == "" {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	// No individual Get endpoint; list and filter by ID.
	selfHostEnrollment, err := e.getSelfHostEnrollment(ctx, cr.Spec.ForProvider.OrgID, externalName)
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, fmt.Errorf("%s: %w", errSelfHostEnrollmentObserve, err)
	}

	cr.Status.AtProvider = selfHostEnrollmentObservation(selfHostEnrollment)
	cr.SetConditions(xpv1.Available())

	return managed.ExternalObservation{ResourceExists: true, ResourceUpToDate: true}, nil
}
func (e *selfHostEnrollmentExternal) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.SelfHostEnrollment)
	if !ok {
		return managed.ExternalCreation{}, fmt.Errorf(errNotSelfHostEnrollment)
	}

	fp := cr.Spec.ForProvider

	req := pgbeam.CreateSelfHostEnrollmentRequest{}
	if fp.RegionLabel != nil {
		req.RegionLabel = fp.RegionLabel
	}
	if fp.Description != nil {
		req.Description = fp.Description
	}
	if fp.ExpiresAt != "" {
		expiresAtTime, err := time.Parse(time.RFC3339, fp.ExpiresAt)
		if err != nil {
			return managed.ExternalCreation{}, fmt.Errorf("%s: invalid expires_at: %w", errSelfHostEnrollmentCreate, err)
		}
		req.ExpiresAt = &expiresAtTime
	}

	resp, err := e.client.Platform.CreateSelfHostEnrollment(ctx, fp.OrgID, req)
	if err != nil {
		return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errSelfHostEnrollmentCreate, err)
	}

	meta.SetExternalName(cr, resp.Enrollment.Id)
	cr.Status.AtProvider = selfHostEnrollmentObservation(&resp.Enrollment)

	connDetails := managed.ConnectionDetails{}
	if resp.Token != "" {
		connDetails["token"] = []byte(resp.Token)
	}
	return managed.ExternalCreation{ConnectionDetails: connDetails}, nil
}
func (e *selfHostEnrollmentExternal) Update(_ context.Context, _ resource.Managed) (managed.ExternalUpdate, error) {
	return managed.ExternalUpdate{}, fmt.Errorf(errSelfHostEnrollmentUpdate)
}
func (e *selfHostEnrollmentExternal) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*v1alpha1.SelfHostEnrollment)
	if !ok {
		return managed.ExternalDelete{}, fmt.Errorf(errNotSelfHostEnrollment)
	}
	if err := e.client.Platform.RevokeSelfHostEnrollment(ctx, cr.Spec.ForProvider.OrgID, meta.GetExternalName(cr)); err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalDelete{}, nil
		}
		return managed.ExternalDelete{}, fmt.Errorf("%s: %w", errSelfHostEnrollmentDelete, err)
	}
	return managed.ExternalDelete{}, nil
}

// getSelfHostEnrollment lists self host enrollments for a org and returns the one matching id.
func (e *selfHostEnrollmentExternal) getSelfHostEnrollment(ctx context.Context, orgID string, id string) (*pgbeam.SelfHostEnrollment, error) {
	resp, err := e.client.Platform.ListSelfHostEnrollments(ctx, orgID)
	if err != nil {
		return nil, err
	}
	for i := range resp.Enrollments {
		if resp.Enrollments[i].Id == id {
			return &resp.Enrollments[i], nil
		}
	}
	return nil, &pgbeam.APIError{StatusCode: 404, Status: "Not Found", Body: fmt.Sprintf("self host enrollment %s not found in org %s", id, orgID)}
}
func selfHostEnrollmentObservation(s *pgbeam.SelfHostEnrollment) v1alpha1.SelfHostEnrollmentAtProvider {
	obs := v1alpha1.SelfHostEnrollmentAtProvider{
		ID:        s.Id,
		CreatedAt: s.CreatedAt.Format(time.RFC3339),
	}
	if s.CreatedBy != nil {
		obs.CreatedBy = *s.CreatedBy
	}
	if s.LastSeenAt != nil {
		obs.LastSeenAt = s.LastSeenAt.Format(time.RFC3339)
	}
	if s.RevokedAt != nil {
		obs.RevokedAt = s.RevokedAt.Format(time.RFC3339)
	}
	return obs
}
