// Code generated by generate-crossplane.ts — DO NOT EDIT.

package controller

import (
	"context"
	"fmt"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/controller"
	"github.com/crossplane/crossplane-runtime/pkg/event"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/pkg/resource"
	pgbeam "github.com/pgbeam/pgbeam-go"
	"github.com/pgbeam/provider-pgbeam/apis/v1alpha1"
	ctrl "sigs.k8s.io/controller-runtime"
	"time"
)

const (
	errNotSpendLimit     = "managed resource is not a SpendLimit"
	errSpendLimitCreate  = "cannot create SpendLimit"
	errSpendLimitUpdate  = "cannot update SpendLimit"
	errSpendLimitDelete  = "cannot soft-delete SpendLimit"
	errSpendLimitObserve = "cannot observe SpendLimit"
)

func SetupSpendLimit(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.SpendLimitGroupKind)
	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		For(&v1alpha1.SpendLimit{}).
		WithOptions(o.ForControllerRuntime()).
		Complete(managed.NewReconciler(mgr,
			resource.ManagedKind(v1alpha1.SpendLimitGroupVersionKind),
			managed.WithExternalConnecter(&spendLimitConnecter{
				connector: connector{
					kube:  mgr.GetClient(),
					usage: resource.NewProviderConfigUsageTracker(mgr.GetClient(), &v1alpha1.ProviderConfigUsage{}),
				},
			}),
			managed.WithLogger(o.Logger.WithValues("controller", name)),
			managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))),
		))
}

type spendLimitConnecter struct{ connector }

func (c *spendLimitConnecter) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cl, err := c.getClient(ctx, mg)
	if err != nil {
		return nil, err
	}
	return &spendLimitExternal{client: cl}, nil
}

type spendLimitExternal struct{ client *pgbeam.Client }

func (e *spendLimitExternal) Disconnect(_ context.Context) error { return nil }

func (e *spendLimitExternal) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.SpendLimit)
	if !ok {
		return managed.ExternalObservation{}, fmt.Errorf(errNotSpendLimit)
	}

	externalName := meta.GetExternalName(cr)
	if externalName == "" {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	spendLimit, err := e.client.Analytics.GetOrganizationPlan(ctx, cr.Spec.ForProvider.OrgID)
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, fmt.Errorf("%s: %w", errSpendLimitObserve, err)
	}

	cr.Status.AtProvider = spendLimitObservation(spendLimit)
	cr.SetConditions(xpv1.Available())

	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: isSpendLimitUpToDate(cr.Spec.ForProvider, spendLimit),
	}, nil
}
func (e *spendLimitExternal) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.SpendLimit)
	if !ok {
		return managed.ExternalCreation{}, fmt.Errorf(errNotSpendLimit)
	}

	fp := cr.Spec.ForProvider
	resp, err := e.client.Analytics.UpdateSpendLimit(ctx, fp.OrgID, pgbeam.UpdateSpendLimitRequest{
		SpendLimit: fp.SpendLimit,
	})
	if err != nil {
		return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errSpendLimitCreate, err)
	}

	meta.SetExternalName(cr, fp.OrgID)
	cr.Status.AtProvider = spendLimitObservation(resp)
	return managed.ExternalCreation{}, nil
}
func (e *spendLimitExternal) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*v1alpha1.SpendLimit)
	if !ok {
		return managed.ExternalUpdate{}, fmt.Errorf(errNotSpendLimit)
	}

	fp := cr.Spec.ForProvider
	if _, err := e.client.Analytics.UpdateSpendLimit(ctx, fp.OrgID, pgbeam.UpdateSpendLimitRequest{
		SpendLimit: fp.SpendLimit,
	}); err != nil {
		return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errSpendLimitUpdate, err)
	}
	return managed.ExternalUpdate{}, nil
}
func (e *spendLimitExternal) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*v1alpha1.SpendLimit)
	if !ok {
		return managed.ExternalDelete{}, fmt.Errorf(errNotSpendLimit)
	}

	fp := cr.Spec.ForProvider
	// Soft delete: disable by setting spend_limit=nil.
	if _, err := e.client.Analytics.UpdateSpendLimit(ctx, fp.OrgID, pgbeam.UpdateSpendLimitRequest{
		SpendLimit: nil,
	}); err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalDelete{}, nil
		}
		return managed.ExternalDelete{}, fmt.Errorf("%s: %w", errSpendLimitDelete, err)
	}
	return managed.ExternalDelete{}, nil
}
func spendLimitObservation(o *pgbeam.OrganizationPlan) v1alpha1.SpendLimitAtProvider {
	obs := v1alpha1.SpendLimitAtProvider{
		OrgID: o.OrgId,
		Plan:  string(o.Plan),
	}
	if o.BillingProvider != nil {
		obs.BillingProvider = string(*o.BillingProvider)
	}
	if o.SubscriptionStatus != nil {
		obs.SubscriptionStatus = string(*o.SubscriptionStatus)
	}
	if o.CurrentPeriodEnd != nil {
		obs.CurrentPeriodEnd = o.CurrentPeriodEnd.Format(time.RFC3339)
	}
	if o.Enabled != nil {
		obs.Enabled = o.Enabled
	}
	if o.CustomPricing != nil {
		obs.CustomPricing = o.CustomPricing
	}
	obs.Limits = &v1alpha1.PlanLimitsObservation{
		QueriesPerDay:    o.Limits.QueriesPerDay,
		MaxProjects:      o.Limits.MaxProjects,
		MaxDatabases:     o.Limits.MaxDatabases,
		MaxConnections:   o.Limits.MaxConnections,
		QueriesPerSecond: o.Limits.QueriesPerSecond,
		BytesPerMonth:    o.Limits.BytesPerMonth,
		MaxQueryShapes:   o.Limits.MaxQueryShapes,
		IncludedSeats:    o.Limits.IncludedSeats,
	}
	if o.CreatedAt != nil {
		obs.CreatedAt = o.CreatedAt.Format(time.RFC3339)
	}
	if o.UpdatedAt != nil {
		obs.UpdatedAt = o.UpdatedAt.Format(time.RFC3339)
	}
	return obs
}
func isSpendLimitUpToDate(fp v1alpha1.SpendLimitForProvider, o *pgbeam.OrganizationPlan) bool {
	if fp.SpendLimit != nil && (o.SpendLimit == nil || *fp.SpendLimit != *o.SpendLimit) {
		return false
	}
	return true
}
