// Code generated by generate-crossplane.ts — DO NOT EDIT.

package controller

import (
	"context"
	"fmt"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	"github.com/crossplane/crossplane-runtime/pkg/controller"
	"github.com/crossplane/crossplane-runtime/pkg/event"
	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/pkg/resource"
	"github.com/pgbeam/provider-pgbeam/apis/v1alpha1"
	pgbeam "go.pgbeam.com/sdk"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"time"
)

const (
	errNotWebhookEndpoint      = "managed resource is not a WebhookEndpoint"
	errWebhookEndpointCreate   = "cannot create WebhookEndpoint"
	errWebhookEndpointUpdate   = "cannot update WebhookEndpoint"
	errWebhookEndpointDelete   = "cannot delete WebhookEndpoint"
	errWebhookEndpointObserve  = "cannot observe WebhookEndpoint"
	errWebhookEndpointPassword = "cannot read database password"
)

func SetupWebhookEndpoint(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.WebhookEndpointGroupKind)
	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		For(&v1alpha1.WebhookEndpoint{}).
		WithOptions(o.ForControllerRuntime()).
		Complete(managed.NewReconciler(mgr,
			resource.ManagedKind(v1alpha1.WebhookEndpointGroupVersionKind),
			managed.WithExternalConnecter(&webhookEndpointConnecter{
				connector: connector{
					kube:  mgr.GetClient(),
					usage: resource.NewProviderConfigUsageTracker(mgr.GetClient(), &v1alpha1.ProviderConfigUsage{}),
				},
			}),
			managed.WithLogger(o.Logger.WithValues("controller", name)),
			managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))),
		))
}

type webhookEndpointConnecter struct{ connector }

func (c *webhookEndpointConnecter) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {
	cl, err := c.getClient(ctx, mg)
	if err != nil {
		return nil, err
	}
	return &webhookEndpointExternal{client: cl, kube: c.kube, connector: &c.connector}, nil
}

type webhookEndpointExternal struct {
	client    *pgbeam.Client
	kube      client.Client
	connector *connector
}

func (e *webhookEndpointExternal) Disconnect(_ context.Context) error { return nil }

func (e *webhookEndpointExternal) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*v1alpha1.WebhookEndpoint)
	if !ok {
		return managed.ExternalObservation{}, fmt.Errorf(errNotWebhookEndpoint)
	}

	externalName := meta.GetExternalName(cr)
	if externalName == "" {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	webhookEndpoint, err := e.client.Webhooks.GetWebhookEndpoint(ctx, cr.Spec.ForProvider.ProjectID, externalName)
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, fmt.Errorf("%s: %w", errWebhookEndpointObserve, err)
	}

	cr.Status.AtProvider = webhookEndpointObservation(webhookEndpoint)
	cr.SetConditions(xpv1.Available())

	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: isWebhookEndpointUpToDate(cr.Spec.ForProvider, webhookEndpoint),
	}, nil
}
func (e *webhookEndpointExternal) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*v1alpha1.WebhookEndpoint)
	if !ok {
		return managed.ExternalCreation{}, fmt.Errorf(errNotWebhookEndpoint)
	}

	fp := cr.Spec.ForProvider
	secret, err := e.connector.getSecretValue(ctx, fp.SecretSecretRef)
	if err != nil {
		return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errWebhookEndpointPassword, err)
	}

	req := pgbeam.WebhookEndpointInput{
		Url:    fp.URL,
		Secret: &secret,
	}
	if fp.Format != "" {
		v := pgbeam.WebhookEndpointInputFormat(fp.Format)
		req.Format = &v
	}
	if fp.EventTypes != nil {
		req.EventTypes = &fp.EventTypes
	}
	if fp.Enabled != nil {
		req.Enabled = fp.Enabled
	}
	if fp.Description != nil {
		req.Description = fp.Description
	}

	webhookEndpoint, err := e.client.Webhooks.CreateWebhookEndpoint(ctx, fp.ProjectID, req)
	if err != nil {
		return managed.ExternalCreation{}, fmt.Errorf("%s: %w", errWebhookEndpointCreate, err)
	}

	meta.SetExternalName(cr, webhookEndpoint.Id)
	cr.Status.AtProvider = webhookEndpointObservation(webhookEndpoint)
	return managed.ExternalCreation{}, nil
}
func (e *webhookEndpointExternal) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*v1alpha1.WebhookEndpoint)
	if !ok {
		return managed.ExternalUpdate{}, fmt.Errorf(errNotWebhookEndpoint)
	}

	fp := cr.Spec.ForProvider
	externalName := meta.GetExternalName(cr)

	webhookEndpoint, err := e.client.Webhooks.GetWebhookEndpoint(ctx, cr.Spec.ForProvider.ProjectID, externalName)
	if err != nil {
		return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errWebhookEndpointObserve, err)
	}

	req := pgbeam.WebhookEndpointInput{}
	needsUpdate := false

	if fp.URL != webhookEndpoint.Url {
		req.Url = fp.URL
		needsUpdate = true
	}
	if fp.Format != string(webhookEndpoint.Format) {
		v := pgbeam.WebhookEndpointInputFormat(fp.Format)
		req.Format = &v
		needsUpdate = true
	}
	if fp.EventTypes != nil {
		req.EventTypes = &fp.EventTypes
		needsUpdate = true
	}
	if fp.Enabled != nil && (*fp.Enabled != webhookEndpoint.Enabled) {
		req.Enabled = fp.Enabled
		needsUpdate = true
	}
	if fp.Description != nil && (webhookEndpoint.Description == nil || *fp.Description != *webhookEndpoint.Description) {
		req.Description = fp.Description
		needsUpdate = true
	}

	secret, err := e.connector.getSecretValue(ctx, fp.SecretSecretRef)
	if err != nil {
		return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errWebhookEndpointPassword, err)
	}
	req.Secret = &secret
	needsUpdate = true

	if needsUpdate {
		if _, err := e.client.Webhooks.UpdateWebhookEndpoint(ctx, fp.ProjectID, externalName, req); err != nil {
			return managed.ExternalUpdate{}, fmt.Errorf("%s: %w", errWebhookEndpointUpdate, err)
		}
	}
	return managed.ExternalUpdate{}, nil
}
func (e *webhookEndpointExternal) Delete(ctx context.Context, mg resource.Managed) (managed.ExternalDelete, error) {
	cr, ok := mg.(*v1alpha1.WebhookEndpoint)
	if !ok {
		return managed.ExternalDelete{}, fmt.Errorf(errNotWebhookEndpoint)
	}
	if err := e.client.Webhooks.DeleteWebhookEndpoint(ctx, cr.Spec.ForProvider.ProjectID, meta.GetExternalName(cr)); err != nil {
		if pgbeam.IsNotFound(err) {
			return managed.ExternalDelete{}, nil
		}
		return managed.ExternalDelete{}, fmt.Errorf("%s: %w", errWebhookEndpointDelete, err)
	}
	return managed.ExternalDelete{}, nil
}
func webhookEndpointObservation(w *pgbeam.WebhookEndpoint) v1alpha1.WebhookEndpointAtProvider {
	obs := v1alpha1.WebhookEndpointAtProvider{
		ID:        w.Id,
		CreatedAt: w.CreatedAt.Format(time.RFC3339),
		UpdatedAt: w.UpdatedAt.Format(time.RFC3339),
	}
	return obs
}
func isWebhookEndpointUpToDate(fp v1alpha1.WebhookEndpointForProvider, w *pgbeam.WebhookEndpoint) bool {
	if fp.URL != w.Url {
		return false
	}
	if fp.Format != "" {
		if fp.Format != string(w.Format) {
			return false
		}
	}
	if fp.EventTypes != nil {
		wTags := w.EventTypes
		if wTags == nil {
			if len(fp.EventTypes) != 0 {
				return false
			}
		} else {
			if len(fp.EventTypes) != len(*wTags) {
				return false
			}
			for i, t := range fp.EventTypes {
				if t != (*wTags)[i] {
					return false
				}
			}
		}
	}
	if fp.Enabled != nil && (*fp.Enabled != w.Enabled) {
		return false
	}
	if fp.Description != nil && (w.Description == nil || *fp.Description != *w.Description) {
		return false
	}
	return true
}
