// Code generated by generate-crossplane.ts — DO NOT EDIT.

// +kubebuilder:object:generate=true
// +groupName=pgbeam.io
// +versionName=v1alpha1
package v1alpha1

import (
	"reflect"

	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

// Package type metadata.
const (
	Group   = "pgbeam.io"
	Version = "v1alpha1"
)

var (
	SchemeGroupVersion = schema.GroupVersion{Group: Group, Version: Version}
	SchemeBuilder      = &scheme.Builder{GroupVersion: SchemeGroupVersion}
	AddToScheme        = SchemeBuilder.AddToScheme
)

func init() {
	SchemeBuilder.Register(
		&Project{}, &ProjectList{},
		&Database{}, &DatabaseList{},
		&Replica{}, &ReplicaList{},
		&CustomDomain{}, &CustomDomainList{},
		&CacheRule{}, &CacheRuleList{},
		&SpendLimit{}, &SpendLimitList{},
		&AgentCredential{}, &AgentCredentialList{},
		&PolicyProfile{}, &PolicyProfileList{},
		&WebhookEndpoint{}, &WebhookEndpointList{},
		&SelfHostEnrollment{}, &SelfHostEnrollmentList{},
		&Honeytoken{}, &HoneytokenList{},
		&ProviderConfig{}, &ProviderConfigList{},
		&ProviderConfigUsage{}, &ProviderConfigUsageList{},
	)
}

// Project type metadata.
var (
	ProjectKind             = reflect.TypeOf(Project{}).Name()
	ProjectGroupKind        = schema.GroupKind{Group: Group, Kind: ProjectKind}.String()
	ProjectKindAPIVersion   = ProjectKind + "." + SchemeGroupVersion.String()
	ProjectGroupVersionKind = SchemeGroupVersion.WithKind(ProjectKind)
)

// Database type metadata.
var (
	DatabaseKind             = reflect.TypeOf(Database{}).Name()
	DatabaseGroupKind        = schema.GroupKind{Group: Group, Kind: DatabaseKind}.String()
	DatabaseKindAPIVersion   = DatabaseKind + "." + SchemeGroupVersion.String()
	DatabaseGroupVersionKind = SchemeGroupVersion.WithKind(DatabaseKind)
)

// Replica type metadata.
var (
	ReplicaKind             = reflect.TypeOf(Replica{}).Name()
	ReplicaGroupKind        = schema.GroupKind{Group: Group, Kind: ReplicaKind}.String()
	ReplicaKindAPIVersion   = ReplicaKind + "." + SchemeGroupVersion.String()
	ReplicaGroupVersionKind = SchemeGroupVersion.WithKind(ReplicaKind)
)

// CustomDomain type metadata.
var (
	CustomDomainKind             = reflect.TypeOf(CustomDomain{}).Name()
	CustomDomainGroupKind        = schema.GroupKind{Group: Group, Kind: CustomDomainKind}.String()
	CustomDomainKindAPIVersion   = CustomDomainKind + "." + SchemeGroupVersion.String()
	CustomDomainGroupVersionKind = SchemeGroupVersion.WithKind(CustomDomainKind)
)

// CacheRule type metadata.
var (
	CacheRuleKind             = reflect.TypeOf(CacheRule{}).Name()
	CacheRuleGroupKind        = schema.GroupKind{Group: Group, Kind: CacheRuleKind}.String()
	CacheRuleKindAPIVersion   = CacheRuleKind + "." + SchemeGroupVersion.String()
	CacheRuleGroupVersionKind = SchemeGroupVersion.WithKind(CacheRuleKind)
)

// SpendLimit type metadata.
var (
	SpendLimitKind             = reflect.TypeOf(SpendLimit{}).Name()
	SpendLimitGroupKind        = schema.GroupKind{Group: Group, Kind: SpendLimitKind}.String()
	SpendLimitKindAPIVersion   = SpendLimitKind + "." + SchemeGroupVersion.String()
	SpendLimitGroupVersionKind = SchemeGroupVersion.WithKind(SpendLimitKind)
)

// AgentCredential type metadata.
var (
	AgentCredentialKind             = reflect.TypeOf(AgentCredential{}).Name()
	AgentCredentialGroupKind        = schema.GroupKind{Group: Group, Kind: AgentCredentialKind}.String()
	AgentCredentialKindAPIVersion   = AgentCredentialKind + "." + SchemeGroupVersion.String()
	AgentCredentialGroupVersionKind = SchemeGroupVersion.WithKind(AgentCredentialKind)
)

// PolicyProfile type metadata.
var (
	PolicyProfileKind             = reflect.TypeOf(PolicyProfile{}).Name()
	PolicyProfileGroupKind        = schema.GroupKind{Group: Group, Kind: PolicyProfileKind}.String()
	PolicyProfileKindAPIVersion   = PolicyProfileKind + "." + SchemeGroupVersion.String()
	PolicyProfileGroupVersionKind = SchemeGroupVersion.WithKind(PolicyProfileKind)
)

// WebhookEndpoint type metadata.
var (
	WebhookEndpointKind             = reflect.TypeOf(WebhookEndpoint{}).Name()
	WebhookEndpointGroupKind        = schema.GroupKind{Group: Group, Kind: WebhookEndpointKind}.String()
	WebhookEndpointKindAPIVersion   = WebhookEndpointKind + "." + SchemeGroupVersion.String()
	WebhookEndpointGroupVersionKind = SchemeGroupVersion.WithKind(WebhookEndpointKind)
)

// SelfHostEnrollment type metadata.
var (
	SelfHostEnrollmentKind             = reflect.TypeOf(SelfHostEnrollment{}).Name()
	SelfHostEnrollmentGroupKind        = schema.GroupKind{Group: Group, Kind: SelfHostEnrollmentKind}.String()
	SelfHostEnrollmentKindAPIVersion   = SelfHostEnrollmentKind + "." + SchemeGroupVersion.String()
	SelfHostEnrollmentGroupVersionKind = SchemeGroupVersion.WithKind(SelfHostEnrollmentKind)
)

// Honeytoken type metadata.
var (
	HoneytokenKind             = reflect.TypeOf(Honeytoken{}).Name()
	HoneytokenGroupKind        = schema.GroupKind{Group: Group, Kind: HoneytokenKind}.String()
	HoneytokenKindAPIVersion   = HoneytokenKind + "." + SchemeGroupVersion.String()
	HoneytokenGroupVersionKind = SchemeGroupVersion.WithKind(HoneytokenKind)
)
