// Code generated by generate-crossplane.ts — DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

// Managed resource interface methods for Project.

func (p *Project) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return p.Status.GetCondition(ct)
}

func (p *Project) SetConditions(c ...xpv1.Condition) {
	p.Status.SetConditions(c...)
}

func (p *Project) GetProviderConfigReference() *xpv1.Reference {
	return p.Spec.ProviderConfigReference
}

func (p *Project) SetProviderConfigReference(ref *xpv1.Reference) {
	p.Spec.ProviderConfigReference = ref
}

func (p *Project) GetDeletionPolicy() xpv1.DeletionPolicy {
	return p.Spec.DeletionPolicy
}

func (p *Project) SetDeletionPolicy(dp xpv1.DeletionPolicy) {
	p.Spec.DeletionPolicy = dp
}

func (p *Project) GetManagementPolicies() xpv1.ManagementPolicies {
	return p.Spec.ManagementPolicies
}

func (p *Project) SetManagementPolicies(mp xpv1.ManagementPolicies) {
	p.Spec.ManagementPolicies = mp
}

func (p *Project) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return p.Spec.WriteConnectionSecretToReference
}

func (p *Project) SetWriteConnectionSecretToReference(ref *xpv1.SecretReference) {
	p.Spec.WriteConnectionSecretToReference = ref
}

func (p *Project) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return p.Spec.PublishConnectionDetailsTo
}

func (p *Project) SetPublishConnectionDetailsTo(ref *xpv1.PublishConnectionDetailsTo) {
	p.Spec.PublishConnectionDetailsTo = ref
}

// Managed resource interface methods for Database.

func (d *Database) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return d.Status.GetCondition(ct)
}

func (d *Database) SetConditions(c ...xpv1.Condition) {
	d.Status.SetConditions(c...)
}

func (d *Database) GetProviderConfigReference() *xpv1.Reference {
	return d.Spec.ProviderConfigReference
}

func (d *Database) SetProviderConfigReference(ref *xpv1.Reference) {
	d.Spec.ProviderConfigReference = ref
}

func (d *Database) GetDeletionPolicy() xpv1.DeletionPolicy {
	return d.Spec.DeletionPolicy
}

func (d *Database) SetDeletionPolicy(dp xpv1.DeletionPolicy) {
	d.Spec.DeletionPolicy = dp
}

func (d *Database) GetManagementPolicies() xpv1.ManagementPolicies {
	return d.Spec.ManagementPolicies
}

func (d *Database) SetManagementPolicies(mp xpv1.ManagementPolicies) {
	d.Spec.ManagementPolicies = mp
}

func (d *Database) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return d.Spec.WriteConnectionSecretToReference
}

func (d *Database) SetWriteConnectionSecretToReference(ref *xpv1.SecretReference) {
	d.Spec.WriteConnectionSecretToReference = ref
}

func (d *Database) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return d.Spec.PublishConnectionDetailsTo
}

func (d *Database) SetPublishConnectionDetailsTo(ref *xpv1.PublishConnectionDetailsTo) {
	d.Spec.PublishConnectionDetailsTo = ref
}

// Managed resource interface methods for Replica.

func (r *Replica) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return r.Status.GetCondition(ct)
}

func (r *Replica) SetConditions(c ...xpv1.Condition) {
	r.Status.SetConditions(c...)
}

func (r *Replica) GetProviderConfigReference() *xpv1.Reference {
	return r.Spec.ProviderConfigReference
}

func (r *Replica) SetProviderConfigReference(ref *xpv1.Reference) {
	r.Spec.ProviderConfigReference = ref
}

func (r *Replica) GetDeletionPolicy() xpv1.DeletionPolicy {
	return r.Spec.DeletionPolicy
}

func (r *Replica) SetDeletionPolicy(dp xpv1.DeletionPolicy) {
	r.Spec.DeletionPolicy = dp
}

func (r *Replica) GetManagementPolicies() xpv1.ManagementPolicies {
	return r.Spec.ManagementPolicies
}

func (r *Replica) SetManagementPolicies(mp xpv1.ManagementPolicies) {
	r.Spec.ManagementPolicies = mp
}

func (r *Replica) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return r.Spec.WriteConnectionSecretToReference
}

func (r *Replica) SetWriteConnectionSecretToReference(ref *xpv1.SecretReference) {
	r.Spec.WriteConnectionSecretToReference = ref
}

func (r *Replica) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return r.Spec.PublishConnectionDetailsTo
}

func (r *Replica) SetPublishConnectionDetailsTo(ref *xpv1.PublishConnectionDetailsTo) {
	r.Spec.PublishConnectionDetailsTo = ref
}

// Managed resource interface methods for CustomDomain.

func (cd *CustomDomain) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return cd.Status.GetCondition(ct)
}

func (cd *CustomDomain) SetConditions(c ...xpv1.Condition) {
	cd.Status.SetConditions(c...)
}

func (cd *CustomDomain) GetProviderConfigReference() *xpv1.Reference {
	return cd.Spec.ProviderConfigReference
}

func (cd *CustomDomain) SetProviderConfigReference(ref *xpv1.Reference) {
	cd.Spec.ProviderConfigReference = ref
}

func (cd *CustomDomain) GetDeletionPolicy() xpv1.DeletionPolicy {
	return cd.Spec.DeletionPolicy
}

func (cd *CustomDomain) SetDeletionPolicy(dp xpv1.DeletionPolicy) {
	cd.Spec.DeletionPolicy = dp
}

func (cd *CustomDomain) GetManagementPolicies() xpv1.ManagementPolicies {
	return cd.Spec.ManagementPolicies
}

func (cd *CustomDomain) SetManagementPolicies(mp xpv1.ManagementPolicies) {
	cd.Spec.ManagementPolicies = mp
}

func (cd *CustomDomain) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return cd.Spec.WriteConnectionSecretToReference
}

func (cd *CustomDomain) SetWriteConnectionSecretToReference(ref *xpv1.SecretReference) {
	cd.Spec.WriteConnectionSecretToReference = ref
}

func (cd *CustomDomain) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return cd.Spec.PublishConnectionDetailsTo
}

func (cd *CustomDomain) SetPublishConnectionDetailsTo(ref *xpv1.PublishConnectionDetailsTo) {
	cd.Spec.PublishConnectionDetailsTo = ref
}

// Managed resource interface methods for CacheRule.

func (cr *CacheRule) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return cr.Status.GetCondition(ct)
}

func (cr *CacheRule) SetConditions(c ...xpv1.Condition) {
	cr.Status.SetConditions(c...)
}

func (cr *CacheRule) GetProviderConfigReference() *xpv1.Reference {
	return cr.Spec.ProviderConfigReference
}

func (cr *CacheRule) SetProviderConfigReference(ref *xpv1.Reference) {
	cr.Spec.ProviderConfigReference = ref
}

func (cr *CacheRule) GetDeletionPolicy() xpv1.DeletionPolicy {
	return cr.Spec.DeletionPolicy
}

func (cr *CacheRule) SetDeletionPolicy(dp xpv1.DeletionPolicy) {
	cr.Spec.DeletionPolicy = dp
}

func (cr *CacheRule) GetManagementPolicies() xpv1.ManagementPolicies {
	return cr.Spec.ManagementPolicies
}

func (cr *CacheRule) SetManagementPolicies(mp xpv1.ManagementPolicies) {
	cr.Spec.ManagementPolicies = mp
}

func (cr *CacheRule) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return cr.Spec.WriteConnectionSecretToReference
}

func (cr *CacheRule) SetWriteConnectionSecretToReference(ref *xpv1.SecretReference) {
	cr.Spec.WriteConnectionSecretToReference = ref
}

func (cr *CacheRule) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return cr.Spec.PublishConnectionDetailsTo
}

func (cr *CacheRule) SetPublishConnectionDetailsTo(ref *xpv1.PublishConnectionDetailsTo) {
	cr.Spec.PublishConnectionDetailsTo = ref
}

// Managed resource interface methods for SpendLimit.

func (sl *SpendLimit) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return sl.Status.GetCondition(ct)
}

func (sl *SpendLimit) SetConditions(c ...xpv1.Condition) {
	sl.Status.SetConditions(c...)
}

func (sl *SpendLimit) GetProviderConfigReference() *xpv1.Reference {
	return sl.Spec.ProviderConfigReference
}

func (sl *SpendLimit) SetProviderConfigReference(ref *xpv1.Reference) {
	sl.Spec.ProviderConfigReference = ref
}

func (sl *SpendLimit) GetDeletionPolicy() xpv1.DeletionPolicy {
	return sl.Spec.DeletionPolicy
}

func (sl *SpendLimit) SetDeletionPolicy(dp xpv1.DeletionPolicy) {
	sl.Spec.DeletionPolicy = dp
}

func (sl *SpendLimit) GetManagementPolicies() xpv1.ManagementPolicies {
	return sl.Spec.ManagementPolicies
}

func (sl *SpendLimit) SetManagementPolicies(mp xpv1.ManagementPolicies) {
	sl.Spec.ManagementPolicies = mp
}

func (sl *SpendLimit) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return sl.Spec.WriteConnectionSecretToReference
}

func (sl *SpendLimit) SetWriteConnectionSecretToReference(ref *xpv1.SecretReference) {
	sl.Spec.WriteConnectionSecretToReference = ref
}

func (sl *SpendLimit) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return sl.Spec.PublishConnectionDetailsTo
}

func (sl *SpendLimit) SetPublishConnectionDetailsTo(ref *xpv1.PublishConnectionDetailsTo) {
	sl.Spec.PublishConnectionDetailsTo = ref
}

// Managed resource interface methods for AgentCredential.

func (ac *AgentCredential) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return ac.Status.GetCondition(ct)
}

func (ac *AgentCredential) SetConditions(c ...xpv1.Condition) {
	ac.Status.SetConditions(c...)
}

func (ac *AgentCredential) GetProviderConfigReference() *xpv1.Reference {
	return ac.Spec.ProviderConfigReference
}

func (ac *AgentCredential) SetProviderConfigReference(ref *xpv1.Reference) {
	ac.Spec.ProviderConfigReference = ref
}

func (ac *AgentCredential) GetDeletionPolicy() xpv1.DeletionPolicy {
	return ac.Spec.DeletionPolicy
}

func (ac *AgentCredential) SetDeletionPolicy(dp xpv1.DeletionPolicy) {
	ac.Spec.DeletionPolicy = dp
}

func (ac *AgentCredential) GetManagementPolicies() xpv1.ManagementPolicies {
	return ac.Spec.ManagementPolicies
}

func (ac *AgentCredential) SetManagementPolicies(mp xpv1.ManagementPolicies) {
	ac.Spec.ManagementPolicies = mp
}

func (ac *AgentCredential) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return ac.Spec.WriteConnectionSecretToReference
}

func (ac *AgentCredential) SetWriteConnectionSecretToReference(ref *xpv1.SecretReference) {
	ac.Spec.WriteConnectionSecretToReference = ref
}

func (ac *AgentCredential) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return ac.Spec.PublishConnectionDetailsTo
}

func (ac *AgentCredential) SetPublishConnectionDetailsTo(ref *xpv1.PublishConnectionDetailsTo) {
	ac.Spec.PublishConnectionDetailsTo = ref
}

// Managed resource interface methods for PolicyProfile.

func (pp *PolicyProfile) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return pp.Status.GetCondition(ct)
}

func (pp *PolicyProfile) SetConditions(c ...xpv1.Condition) {
	pp.Status.SetConditions(c...)
}

func (pp *PolicyProfile) GetProviderConfigReference() *xpv1.Reference {
	return pp.Spec.ProviderConfigReference
}

func (pp *PolicyProfile) SetProviderConfigReference(ref *xpv1.Reference) {
	pp.Spec.ProviderConfigReference = ref
}

func (pp *PolicyProfile) GetDeletionPolicy() xpv1.DeletionPolicy {
	return pp.Spec.DeletionPolicy
}

func (pp *PolicyProfile) SetDeletionPolicy(dp xpv1.DeletionPolicy) {
	pp.Spec.DeletionPolicy = dp
}

func (pp *PolicyProfile) GetManagementPolicies() xpv1.ManagementPolicies {
	return pp.Spec.ManagementPolicies
}

func (pp *PolicyProfile) SetManagementPolicies(mp xpv1.ManagementPolicies) {
	pp.Spec.ManagementPolicies = mp
}

func (pp *PolicyProfile) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return pp.Spec.WriteConnectionSecretToReference
}

func (pp *PolicyProfile) SetWriteConnectionSecretToReference(ref *xpv1.SecretReference) {
	pp.Spec.WriteConnectionSecretToReference = ref
}

func (pp *PolicyProfile) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return pp.Spec.PublishConnectionDetailsTo
}

func (pp *PolicyProfile) SetPublishConnectionDetailsTo(ref *xpv1.PublishConnectionDetailsTo) {
	pp.Spec.PublishConnectionDetailsTo = ref
}

// Managed resource interface methods for WebhookEndpoint.

func (we *WebhookEndpoint) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return we.Status.GetCondition(ct)
}

func (we *WebhookEndpoint) SetConditions(c ...xpv1.Condition) {
	we.Status.SetConditions(c...)
}

func (we *WebhookEndpoint) GetProviderConfigReference() *xpv1.Reference {
	return we.Spec.ProviderConfigReference
}

func (we *WebhookEndpoint) SetProviderConfigReference(ref *xpv1.Reference) {
	we.Spec.ProviderConfigReference = ref
}

func (we *WebhookEndpoint) GetDeletionPolicy() xpv1.DeletionPolicy {
	return we.Spec.DeletionPolicy
}

func (we *WebhookEndpoint) SetDeletionPolicy(dp xpv1.DeletionPolicy) {
	we.Spec.DeletionPolicy = dp
}

func (we *WebhookEndpoint) GetManagementPolicies() xpv1.ManagementPolicies {
	return we.Spec.ManagementPolicies
}

func (we *WebhookEndpoint) SetManagementPolicies(mp xpv1.ManagementPolicies) {
	we.Spec.ManagementPolicies = mp
}

func (we *WebhookEndpoint) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return we.Spec.WriteConnectionSecretToReference
}

func (we *WebhookEndpoint) SetWriteConnectionSecretToReference(ref *xpv1.SecretReference) {
	we.Spec.WriteConnectionSecretToReference = ref
}

func (we *WebhookEndpoint) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return we.Spec.PublishConnectionDetailsTo
}

func (we *WebhookEndpoint) SetPublishConnectionDetailsTo(ref *xpv1.PublishConnectionDetailsTo) {
	we.Spec.PublishConnectionDetailsTo = ref
}

// Managed resource interface methods for SelfHostEnrollment.

func (she *SelfHostEnrollment) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return she.Status.GetCondition(ct)
}

func (she *SelfHostEnrollment) SetConditions(c ...xpv1.Condition) {
	she.Status.SetConditions(c...)
}

func (she *SelfHostEnrollment) GetProviderConfigReference() *xpv1.Reference {
	return she.Spec.ProviderConfigReference
}

func (she *SelfHostEnrollment) SetProviderConfigReference(ref *xpv1.Reference) {
	she.Spec.ProviderConfigReference = ref
}

func (she *SelfHostEnrollment) GetDeletionPolicy() xpv1.DeletionPolicy {
	return she.Spec.DeletionPolicy
}

func (she *SelfHostEnrollment) SetDeletionPolicy(dp xpv1.DeletionPolicy) {
	she.Spec.DeletionPolicy = dp
}

func (she *SelfHostEnrollment) GetManagementPolicies() xpv1.ManagementPolicies {
	return she.Spec.ManagementPolicies
}

func (she *SelfHostEnrollment) SetManagementPolicies(mp xpv1.ManagementPolicies) {
	she.Spec.ManagementPolicies = mp
}

func (she *SelfHostEnrollment) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return she.Spec.WriteConnectionSecretToReference
}

func (she *SelfHostEnrollment) SetWriteConnectionSecretToReference(ref *xpv1.SecretReference) {
	she.Spec.WriteConnectionSecretToReference = ref
}

func (she *SelfHostEnrollment) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return she.Spec.PublishConnectionDetailsTo
}

func (she *SelfHostEnrollment) SetPublishConnectionDetailsTo(ref *xpv1.PublishConnectionDetailsTo) {
	she.Spec.PublishConnectionDetailsTo = ref
}

// Managed resource interface methods for Honeytoken.

func (h *Honeytoken) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return h.Status.GetCondition(ct)
}

func (h *Honeytoken) SetConditions(c ...xpv1.Condition) {
	h.Status.SetConditions(c...)
}

func (h *Honeytoken) GetProviderConfigReference() *xpv1.Reference {
	return h.Spec.ProviderConfigReference
}

func (h *Honeytoken) SetProviderConfigReference(ref *xpv1.Reference) {
	h.Spec.ProviderConfigReference = ref
}

func (h *Honeytoken) GetDeletionPolicy() xpv1.DeletionPolicy {
	return h.Spec.DeletionPolicy
}

func (h *Honeytoken) SetDeletionPolicy(dp xpv1.DeletionPolicy) {
	h.Spec.DeletionPolicy = dp
}

func (h *Honeytoken) GetManagementPolicies() xpv1.ManagementPolicies {
	return h.Spec.ManagementPolicies
}

func (h *Honeytoken) SetManagementPolicies(mp xpv1.ManagementPolicies) {
	h.Spec.ManagementPolicies = mp
}

func (h *Honeytoken) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return h.Spec.WriteConnectionSecretToReference
}

func (h *Honeytoken) SetWriteConnectionSecretToReference(ref *xpv1.SecretReference) {
	h.Spec.WriteConnectionSecretToReference = ref
}

func (h *Honeytoken) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return h.Spec.PublishConnectionDetailsTo
}

func (h *Honeytoken) SetPublishConnectionDetailsTo(ref *xpv1.PublishConnectionDetailsTo) {
	h.Spec.PublishConnectionDetailsTo = ref
}
