// Code generated by generate-crossplane.ts — DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ============================================================================
// Project
// ============================================================================

// ProjectDatabaseSpec defines the request body for registering an upstream database.
type ProjectDatabaseSpec struct {

	// Host is the postgresql host.
	// +kubebuilder:validation:Required
	Host string `json:"host"`

	// Port is the postgresql port.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=65535
	Port int `json:"port"`

	// Name is the postgresql database name.
	// +kubebuilder:validation:Required
	Name string `json:"name"`

	// Username is the postgresql username.
	// +kubebuilder:validation:Required
	Username string `json:"username"`

	// SSLMode is the postgresql ssl connection mode.
	// +optional
	// +kubebuilder:validation:Enum=disable;allow;prefer;require;verify-ca;verify-full
	SSLMode *string `json:"sslMode,omitempty"`

	// Role is the database role. primary receives writes, replicas receive reads.
	// +optional
	// +kubebuilder:validation:Enum=primary;replica
	// +kubebuilder:default=primary
	Role *string `json:"role,omitempty"`

	// PoolRegion is the region where the connection pool is maintained (near the database). when set and different from the client's edge region, queries are relayed through the pool region's data plane. empty means direct connection.
	// +optional
	PoolRegion *string `json:"poolRegion,omitempty"`

	// QueryTimeoutMs is the query timeout in milliseconds. when set (> 0), the proxy sends set statement_timeout on upstream connections. 0 means disabled (default).
	// +optional
	// +kubebuilder:default=0
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=300000
	QueryTimeoutMs *int `json:"queryTimeoutMs,omitempty"`

	// AutoReadRouting is the when enabled and replicas are configured, select queries automatically route to read replicas without requiring the @pgbeam:replica sql annotation.
	// +optional
	// +kubebuilder:default=false
	AutoReadRouting *bool `json:"autoReadRouting,omitempty"`

	// CacheConfig is the query cache configuration.
	// +optional
	CacheConfig *CacheConfigSpec `json:"cacheConfig,omitempty"`

	// PoolConfig is the connection pool configuration.
	// +optional
	PoolConfig *PoolConfigSpec `json:"poolConfig,omitempty"`

	// PasswordSecretRef is the postgresql password. stored encrypted at rest.
	// +kubebuilder:validation:Required
	PasswordSecretRef xpv1.SecretKeySelector `json:"passwordSecretRef"`
}

// CacheConfigSpec defines the query cache configuration.
type CacheConfigSpec struct {

	// Enabled is the whether query caching is enabled. when false, all queries bypass the cache.
	// +kubebuilder:validation:Required
	// +kubebuilder:default=true
	Enabled bool `json:"enabled"`

	// TTLSeconds is the cache ttl in seconds for query results.
	// +kubebuilder:validation:Required
	// +kubebuilder:default=60
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=86400
	TTLSeconds int `json:"ttlSeconds"`

	// MaxEntries is the maximum number of cached query results.
	// +kubebuilder:validation:Required
	// +kubebuilder:default=10000
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=1000000
	MaxEntries int `json:"maxEntries"`

	// SWRSeconds is the stale-while-revalidate window in seconds.
	// +kubebuilder:validation:Required
	// +kubebuilder:default=30
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=86400
	SWRSeconds int `json:"swrSeconds"`
}

// PoolConfigSpec defines the connection pool configuration.
type PoolConfigSpec struct {

	// PoolSize is the maximum connections in the pool.
	// +kubebuilder:validation:Required
	// +kubebuilder:default=10
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=10000
	PoolSize int `json:"poolSize"`

	// MinPoolSize is the minimum idle connections maintained.
	// +kubebuilder:validation:Required
	// +kubebuilder:default=1
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=10000
	MinPoolSize int `json:"minPoolSize"`

	// PoolMode is the connection pool mode.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=session;transaction;statement
	PoolMode string `json:"poolMode"`

	// MaxActive is the maximum concurrent upstream connections per pool.
	// +optional
	// +kubebuilder:default=200
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=10000
	MaxActive *int `json:"maxActive,omitempty"`
}

// ProjectForProvider defines the desired state of a Project.
type ProjectForProvider struct {
	// OrgID is the better auth organization id that owns this project.
	// +kubebuilder:validation:Required
	// +immutable
	OrgID string `json:"orgID"`

	// Name is the human-readable project name.
	// +kubebuilder:validation:Required
	Name string `json:"name"`

	// Description is the optional project description.
	// +optional
	Description *string `json:"description,omitempty"`

	// Tags is the user-defined labels applied to the project.
	// +optional
	Tags []string `json:"tags,omitempty"`

	// Cloud is the cloud provider where the project runs.
	// +immutable
	// +optional
	// +kubebuilder:validation:Enum=aws;azure;gcp
	Cloud string `json:"cloud,omitempty"`

	// QueriesPerSecond is the maximum queries per second for this project. 0 means unlimited.
	// +optional
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=2147483647
	QueriesPerSecond *int32 `json:"queriesPerSecond,omitempty"`

	// BurstSize is the burst allowance above the steady-state rate. 0 uses queries_per_second as burst.
	// +optional
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=2147483647
	BurstSize *int32 `json:"burstSize,omitempty"`

	// MaxConnections is the maximum concurrent proxy connections. 0 means unlimited.
	// +optional
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=2147483647
	MaxConnections *int32 `json:"maxConnections,omitempty"`

	// AllowedCidrs is the ip allowlist as cidr ranges (e.g., ["10.0.0.0/8", "203.0.113.5/32"]). when non-empty, only connections from matching ips are accepted. empty array means all ips are allowed (default).
	// +optional
	AllowedCidrs []string `json:"allowedCidrs,omitempty"`

	// Status is the project lifecycle status.
	// +optional
	// +kubebuilder:validation:Enum=active;suspended;deleted
	Status string `json:"status,omitempty"`

	// Database is the request body for registering an upstream database.
	// +kubebuilder:validation:Required
	// +immutable
	Database ProjectDatabaseSpec `json:"database"`
}

// ProjectAtProvider defines the observed state of a Project.
type ProjectAtProvider struct {
	// ID is the PgBeam project ID.
	ID string `json:"id,omitempty"`

	// ProxyHost is the proxy hostname for connecting through pgbeam (e.g., myproject.aws.pgbeam.app).
	ProxyHost string `json:"proxyHost,omitempty"`

	// DatabaseCount is the number of databases attached to this project.
	DatabaseCount int `json:"databaseCount,omitempty"`

	// ActiveConnections is the current active connections (latest metrics snapshot). 0 when no metrics data.
	ActiveConnections int `json:"activeConnections,omitempty"`

	// CreatedAt is the when the project was created.
	CreatedAt string `json:"createdAt,omitempty"`

	// UpdatedAt is the when the project was last updated.
	UpdatedAt string `json:"updatedAt,omitempty"`

	// PrimaryDatabaseID is the id of the primary database created with this project.
	PrimaryDatabaseID string `json:"primaryDatabaseID,omitempty"`
}

// ProjectSpec defines the desired state of a Project.
type ProjectSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       ProjectForProvider `json:"forProvider"`
}

// ProjectStatus defines the observed state of a Project.
type ProjectStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          ProjectAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// Project is a managed resource that represents a PgBeam Project.
type Project struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ProjectSpec   `json:"spec"`
	Status ProjectStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectList contains a list of Projects.
type ProjectList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Project `json:"items"`
}

// ============================================================================
// Database
// ============================================================================

// DatabaseForProvider defines the desired state of a Database.
type DatabaseForProvider struct {
	// ProjectID is the owning project id.
	// +kubebuilder:validation:Required
	// +immutable
	ProjectID string `json:"projectID"`

	// Host is the postgresql host.
	// +kubebuilder:validation:Required
	Host string `json:"host"`

	// Port is the postgresql port.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=65535
	Port int `json:"port"`

	// Name is the postgresql database name.
	// +kubebuilder:validation:Required
	Name string `json:"name"`

	// Username is the postgresql username.
	// +kubebuilder:validation:Required
	Username string `json:"username"`

	// SSLMode is the postgresql ssl connection mode.
	// +optional
	// +kubebuilder:validation:Enum=disable;allow;prefer;require;verify-ca;verify-full
	SSLMode string `json:"sslMode,omitempty"`

	// Role is the database role. primary receives writes, replicas receive reads.
	// +optional
	// +kubebuilder:validation:Enum=primary;replica
	// +kubebuilder:default=primary
	Role string `json:"role,omitempty"`

	// PoolRegion is the region where the connection pool is maintained (near the database). when set and different from the client's edge region, queries are relayed through the pool region's data plane. empty means direct connection.
	// +optional
	PoolRegion *string `json:"poolRegion,omitempty"`

	// QueryTimeoutMs is the query timeout in milliseconds. when set (> 0), the proxy sends set statement_timeout on upstream connections. 0 means disabled (default).
	// +optional
	// +kubebuilder:default=0
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=300000
	QueryTimeoutMs *int `json:"queryTimeoutMs,omitempty"`

	// AutoReadRouting is the when enabled and replicas are configured, select queries automatically route to read replicas without requiring the @pgbeam:replica sql annotation.
	// +optional
	// +kubebuilder:default=false
	AutoReadRouting *bool `json:"autoReadRouting,omitempty"`

	// CacheConfig is the query cache configuration.
	// +optional
	CacheConfig *CacheConfigSpec `json:"cacheConfig,omitempty"`

	// PoolConfig is the connection pool configuration.
	// +optional
	PoolConfig *PoolConfigSpec `json:"poolConfig,omitempty"`

	// PasswordSecretRef is the postgresql password. stored encrypted at rest.
	// +kubebuilder:validation:Required
	PasswordSecretRef xpv1.SecretKeySelector `json:"passwordSecretRef"`
}

// DatabaseAtProvider defines the observed state of a Database.
type DatabaseAtProvider struct {
	// ID is the PgBeam database ID.
	ID string `json:"id,omitempty"`

	// ConnectionString is the connection string for connecting through pgbeam proxy. password is replaced with a placeholder.
	ConnectionString string `json:"connectionString,omitempty"`

	// CreatedAt is the when the database registration was created.
	CreatedAt string `json:"createdAt,omitempty"`

	// UpdatedAt is the when the database registration was last updated.
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// DatabaseSpec defines the desired state of a Database.
type DatabaseSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       DatabaseForProvider `json:"forProvider"`
}

// DatabaseStatus defines the observed state of a Database.
type DatabaseStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          DatabaseAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// Database is a managed resource that represents a PgBeam Database.
type Database struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DatabaseSpec   `json:"spec"`
	Status DatabaseStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DatabaseList contains a list of Databases.
type DatabaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Database `json:"items"`
}

// ============================================================================
// Replica
// ============================================================================

// ReplicaForProvider defines the desired state of a Replica.
type ReplicaForProvider struct {
	// DatabaseID is the parent database id.
	// +kubebuilder:validation:Required
	// +immutable
	DatabaseID string `json:"databaseID"`

	// Host is the postgresql replica host.
	// +kubebuilder:validation:Required
	// +immutable
	Host string `json:"host"`

	// Port is the postgresql replica port.
	// +kubebuilder:validation:Required
	// +immutable
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=65535
	Port int `json:"port"`

	// SSLMode is the postgresql ssl connection mode.
	// +immutable
	// +optional
	// +kubebuilder:validation:Enum=disable;allow;prefer;require;verify-ca;verify-full
	SSLMode string `json:"sslMode,omitempty"`
}

// ReplicaAtProvider defines the observed state of a Replica.
type ReplicaAtProvider struct {
	// ID is the PgBeam replica ID.
	ID string `json:"id,omitempty"`

	// CreatedAt is the when the replica was created.
	CreatedAt string `json:"createdAt,omitempty"`

	// UpdatedAt is the when the replica was last updated.
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// ReplicaSpec defines the desired state of a Replica.
type ReplicaSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       ReplicaForProvider `json:"forProvider"`
}

// ReplicaStatus defines the observed state of a Replica.
type ReplicaStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          ReplicaAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// Replica is a managed resource that represents a PgBeam Replica.
// All fields are immutable; any change triggers recreation.
type Replica struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ReplicaSpec   `json:"spec"`
	Status ReplicaStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ReplicaList contains a list of Replicas.
type ReplicaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Replica `json:"items"`
}

// ============================================================================
// CustomDomain
// ============================================================================

// CustomDomainForProvider defines the desired state of a CustomDomain.
type CustomDomainForProvider struct {
	// ProjectID is the owning project id.
	// +kubebuilder:validation:Required
	// +immutable
	ProjectID string `json:"projectID"`

	// Domain is the the custom domain name.
	// +kubebuilder:validation:Required
	// +immutable
	Domain string `json:"domain"`
}

// DNSInstructionsObservation dns records the user needs to create for domain verification.
type DNSInstructionsObservation struct {

	// CnameHost is the the cname record host.
	CnameHost string `json:"cnameHost,omitempty"`

	// CnameTarget is the the cname record target.
	CnameTarget string `json:"cnameTarget,omitempty"`

	// TxtHost is the the txt record host for verification.
	TxtHost string `json:"txtHost,omitempty"`

	// TxtValue is the the txt record value for verification.
	TxtValue string `json:"txtValue,omitempty"`

	// ACMECnameHost is the the cname record host for acme tls certificate issuance.
	ACMECnameHost string `json:"acmeCnameHost,omitempty"`

	// ACMECnameTarget is the the cname target for acme challenge delegation.
	ACMECnameTarget string `json:"acmeCnameTarget,omitempty"`
}

// CustomDomainAtProvider defines the observed state of a CustomDomain.
type CustomDomainAtProvider struct {
	// ID is the PgBeam custom domain ID.
	ID string `json:"id,omitempty"`

	// Verified is the whether dns ownership has been verified.
	Verified *bool `json:"verified,omitempty"`

	// VerifiedAt is the when dns verification was completed.
	VerifiedAt string `json:"verifiedAt,omitempty"`

	// TLSCertExpiry is the when the tls certificate expires.
	TLSCertExpiry string `json:"tlsCertExpiry,omitempty"`

	// DNSVerificationToken is the token value for the dns txt record verification.
	DNSVerificationToken string `json:"dnsVerificationToken,omitempty"`

	// DNSInstructions is the dns records the user needs to create for domain verification.
	DNSInstructions *DNSInstructionsObservation `json:"dnsInstructions,omitempty"`

	// CreatedAt is the when the custom domain was created.
	CreatedAt string `json:"createdAt,omitempty"`

	// UpdatedAt is the when the custom domain was last updated.
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// CustomDomainSpec defines the desired state of a CustomDomain.
type CustomDomainSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       CustomDomainForProvider `json:"forProvider"`
}

// CustomDomainStatus defines the observed state of a CustomDomain.
type CustomDomainStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          CustomDomainAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// CustomDomain is a managed resource that represents a PgBeam Custom Domain.
// All fields are immutable; any change triggers recreation.
type CustomDomain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CustomDomainSpec   `json:"spec"`
	Status CustomDomainStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomDomainList contains a list of CustomDomains.
type CustomDomainList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomDomain `json:"items"`
}

// ============================================================================
// CacheRule
// ============================================================================

// CacheRuleForProvider defines the desired state of a CacheRule.
type CacheRuleForProvider struct {
	// QueryHash is the queryhash path parameter.
	// +kubebuilder:validation:Required
	// +immutable
	QueryHash string `json:"queryHash"`

	// DatabaseID is the databaseid path parameter.
	// +kubebuilder:validation:Required
	// +immutable
	DatabaseID string `json:"databaseID"`

	// ProjectID is the projectid path parameter.
	// +kubebuilder:validation:Required
	// +immutable
	ProjectID string `json:"projectID"`

	// CacheEnabled is the whether caching is enabled for this query shape.
	// +kubebuilder:validation:Required
	CacheEnabled bool `json:"cacheEnabled"`

	// CacheTTLSeconds is the ttl override in seconds. null means use project default.
	// +optional
	// +kubebuilder:validation:Minimum=0
	CacheTTLSeconds *int `json:"cacheTTLSeconds,omitempty"`

	// CacheSWRSeconds is the swr override in seconds. null means use project default.
	// +optional
	// +kubebuilder:validation:Minimum=0
	CacheSWRSeconds *int `json:"cacheSWRSeconds,omitempty"`
}

// CacheRuleAtProvider defines the observed state of a CacheRule.
type CacheRuleAtProvider struct {
	// ID is the PgBeam cache rule ID.
	ID string `json:"id,omitempty"`

	// QueryHash is the xxhash64 hex of the normalized sql.
	QueryHash string `json:"queryHash,omitempty"`

	// NormalizedSQL is the sql with literals replaced by $n placeholders.
	NormalizedSQL string `json:"normalizedSQL,omitempty"`

	// QueryType is the query classification.
	QueryType string `json:"queryType,omitempty"`

	// CallCount is the total number of executions observed.
	CallCount int64 `json:"callCount,omitempty"`

	// AvgLatencyMs is the average query latency in milliseconds.
	AvgLatencyMs float64 `json:"avgLatencyMs,omitempty"`

	// P95LatencyMs is the 95th percentile latency in milliseconds.
	P95LatencyMs float64 `json:"p95LatencyMs,omitempty"`

	// AvgResponseBytes is the average response size in bytes.
	AvgResponseBytes int64 `json:"avgResponseBytes,omitempty"`

	// StabilityRate is the response stability rate (0.0 to 1.0). higher means more stable.
	StabilityRate float64 `json:"stabilityRate,omitempty"`

	// Recommendation is the cache recommendation based on frequency, latency, and stability.
	Recommendation string `json:"recommendation,omitempty"`

	// FirstSeenAt is the when this query was first observed.
	FirstSeenAt string `json:"firstSeenAt,omitempty"`

	// LastSeenAt is the when this query was last observed.
	LastSeenAt string `json:"lastSeenAt,omitempty"`
}

// CacheRuleSpec defines the desired state of a CacheRule.
type CacheRuleSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       CacheRuleForProvider `json:"forProvider"`
}

// CacheRuleStatus defines the observed state of a CacheRule.
type CacheRuleStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          CacheRuleAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// CacheRule is a managed resource that represents a PgBeam Cache Rule.
// Deletion is a soft delete that sets cache_enabled=false.
type CacheRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CacheRuleSpec   `json:"spec"`
	Status CacheRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CacheRuleList contains a list of CacheRules.
type CacheRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CacheRule `json:"items"`
}

// ============================================================================
// SpendLimit
// ============================================================================

// SpendLimitForProvider defines the desired state of a SpendLimit.
type SpendLimitForProvider struct {
	// OrgID is the orgid path parameter.
	// +kubebuilder:validation:Required
	// +immutable
	OrgID string `json:"orgID"`

	// SpendLimit is the monthly spend limit in dollars. null means no limit.
	// +optional
	SpendLimit *float64 `json:"spendLimit,omitempty"`
}

// PlanLimitsObservation effective usage limits enforced for an organization plan.
type PlanLimitsObservation struct {

	// QueriesPerDay is the maximum queries per day across all projects. 0 means unlimited.
	QueriesPerDay int64 `json:"queriesPerDay,omitempty"`

	// MaxProjects is the maximum number of active projects.
	MaxProjects int `json:"maxProjects,omitempty"`

	// MaxDatabases is the maximum databases per project.
	MaxDatabases int `json:"maxDatabases,omitempty"`

	// MaxConnections is the maximum concurrent connections per project.
	MaxConnections int `json:"maxConnections,omitempty"`

	// QueriesPerSecond is the maximum queries per second per project.
	QueriesPerSecond int `json:"queriesPerSecond,omitempty"`

	// BytesPerMonth is the monthly data transfer quota in bytes. 0 means unlimited.
	BytesPerMonth int64 `json:"bytesPerMonth,omitempty"`

	// MaxQueryShapes is the maximum query shapes in cache rules. 0 means unlimited.
	MaxQueryShapes int `json:"maxQueryShapes,omitempty"`

	// IncludedSeats is the number of seats included in the plan.
	IncludedSeats int `json:"includedSeats,omitempty"`
}

// SpendLimitAtProvider defines the observed state of a SpendLimit.
type SpendLimitAtProvider struct {
	// ID is the PgBeam spend limit ID.
	ID string `json:"id,omitempty"`

	// OrgID is the organization identifier the plan applies to.
	OrgID string `json:"orgID,omitempty"`

	// Plan is the current plan tier.
	Plan string `json:"plan,omitempty"`

	// BillingProvider is the which billing provider manages this organization's subscription.
	BillingProvider string `json:"billingProvider,omitempty"`

	// SubscriptionStatus is the stripe subscription status.
	SubscriptionStatus string `json:"subscriptionStatus,omitempty"`

	// CurrentPeriodEnd is the end of current billing period.
	CurrentPeriodEnd string `json:"currentPeriodEnd,omitempty"`

	// Enabled is the whether the organization billing is active (false = suspended).
	Enabled *bool `json:"enabled,omitempty"`

	// CustomPricing is the whether the organization has custom enterprise pricing.
	CustomPricing *bool `json:"customPricing,omitempty"`

	// Limits is the effective usage limits enforced for an organization plan.
	Limits *PlanLimitsObservation `json:"limits,omitempty"`

	// CreatedAt is the when the billing record was created.
	CreatedAt string `json:"createdAt,omitempty"`

	// UpdatedAt is the when the billing record was last updated.
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// SpendLimitSpec defines the desired state of a SpendLimit.
type SpendLimitSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       SpendLimitForProvider `json:"forProvider"`
}

// SpendLimitStatus defines the observed state of a SpendLimit.
type SpendLimitStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          SpendLimitAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// SpendLimit is a managed resource that represents a PgBeam Spend Limit.
// Deletion is a soft delete that sets spend_limit=null.
type SpendLimit struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SpendLimitSpec   `json:"spec"`
	Status SpendLimitStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SpendLimitList contains a list of SpendLimits.
type SpendLimitList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SpendLimit `json:"items"`
}
