// Code generated by generate-crossplane.ts — DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ============================================================================
// Project
// ============================================================================

// CidrEntryParameters is one entry of ip filtering rules as cidr ranges with optional labels. when non-empty, only connections from matching ips are accepted. empty array means all ips are allowed (default). both ipv4 (e.g. 10.0.0.0/8) and ipv6 (e.g. 2001:db8::/32) are supported.
type CidrEntryParameters struct {

	// Cidr is the cidr range in ipv4 (e.g. 203.0.113.0/24) or ipv6 (e.g. 2001:db8::/32) notation. a plain ip without prefix length defaults to /32 (ipv4) or /128 (ipv6).
	// +kubebuilder:validation:Required
	Cidr string `json:"cidr"`

	// Label is the optional human-readable label for this cidr entry (e.g. "office", "vpc").
	// +optional
	Label *string `json:"label,omitempty"`
}

// ProjectDatabaseSpec defines the request body for registering an upstream database.
type ProjectDatabaseSpec struct {

	// Host is the postgresql host.
	// +kubebuilder:validation:Required
	Host string `json:"host"`

	// Port is the postgresql port.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=65535
	Port int `json:"port"`

	// Name is the postgresql database name.
	// +kubebuilder:validation:Required
	Name string `json:"name"`

	// Username is the postgresql username.
	// +kubebuilder:validation:Required
	Username string `json:"username"`

	// SSLMode is the postgresql ssl connection mode.
	// +optional
	// +kubebuilder:validation:Enum=disable;allow;prefer;require;verify-ca;verify-full
	SSLMode *string `json:"sslMode,omitempty"`

	// Role is the database role. primary receives writes, replicas receive reads.
	// +optional
	// +kubebuilder:validation:Enum=primary;replica
	// +kubebuilder:default=primary
	Role *string `json:"role,omitempty"`

	// PoolRegion is the region where the connection pool is maintained (near the database). when set and different from the client's edge region, queries are relayed through the pool region's data plane. empty means direct connection.
	// +optional
	PoolRegion *string `json:"poolRegion,omitempty"`

	// QueryTimeoutMs is the query timeout in milliseconds. when set (> 0), the proxy sends set statement_timeout on upstream connections. 0 means disabled (default).
	// +optional
	// +kubebuilder:default=0
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=300000
	QueryTimeoutMs *int `json:"queryTimeoutMs,omitempty"`

	// AutoReadRouting is the when enabled and replicas are configured, select queries automatically route to read replicas without requiring the @pgbeam:replica sql annotation.
	// +optional
	// +kubebuilder:default=false
	AutoReadRouting *bool `json:"autoReadRouting,omitempty"`

	// CacheConfig is the query cache configuration.
	// +optional
	CacheConfig *CacheConfigSpec `json:"cacheConfig,omitempty"`

	// PoolConfig is the connection pool configuration.
	// +optional
	PoolConfig *PoolConfigSpec `json:"poolConfig,omitempty"`

	// PasswordSecretRef is the postgresql password. stored encrypted at rest.
	// +kubebuilder:validation:Required
	PasswordSecretRef xpv1.SecretKeySelector `json:"passwordSecretRef"`
}

// CacheConfigSpec defines the query cache configuration.
type CacheConfigSpec struct {

	// Enabled is the whether query caching is enabled. when false, all queries bypass the cache.
	// +kubebuilder:validation:Required
	// +kubebuilder:default=true
	Enabled bool `json:"enabled"`

	// TTLSeconds is the cache ttl in seconds for query results.
	// +kubebuilder:validation:Required
	// +kubebuilder:default=60
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=86400
	TTLSeconds int `json:"ttlSeconds"`

	// MaxEntries is the maximum number of cached query results.
	// +kubebuilder:validation:Required
	// +kubebuilder:default=10000
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=1000000
	MaxEntries int `json:"maxEntries"`

	// SWRSeconds is the stale-while-revalidate window in seconds.
	// +kubebuilder:validation:Required
	// +kubebuilder:default=30
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=86400
	SWRSeconds int `json:"swrSeconds"`
}

// PoolConfigSpec defines the connection pool configuration.
type PoolConfigSpec struct {

	// PoolSize is the maximum connections in the pool.
	// +kubebuilder:validation:Required
	// +kubebuilder:default=10
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=10000
	PoolSize int `json:"poolSize"`

	// MinPoolSize is the minimum idle connections maintained.
	// +kubebuilder:validation:Required
	// +kubebuilder:default=1
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=10000
	MinPoolSize int `json:"minPoolSize"`

	// PoolMode is the connection pool mode.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=session;transaction;statement
	PoolMode string `json:"poolMode"`

	// MaxActive is the maximum concurrent upstream connections per pool.
	// +optional
	// +kubebuilder:default=200
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=10000
	MaxActive *int `json:"maxActive,omitempty"`
}

// ProjectForProvider defines the desired state of a Project.
type ProjectForProvider struct {
	// OrgID is the better auth organization id that owns this project.
	// +kubebuilder:validation:Required
	// +immutable
	OrgID string `json:"orgID"`

	// Name is the human-readable project name.
	// +kubebuilder:validation:Required
	Name string `json:"name"`

	// Description is the optional project description.
	// +optional
	Description *string `json:"description,omitempty"`

	// Tags is the user-defined labels applied to the project.
	// +optional
	Tags []string `json:"tags,omitempty"`

	// Cloud is the cloud provider where the project runs.
	// +immutable
	// +optional
	// +kubebuilder:validation:Enum=aws;azure;gcp
	Cloud string `json:"cloud,omitempty"`

	// SelfHosted is the when true, this project's data plane runs in the customer's own vpc/cluster (byoc): the control plane does not provision hosted infra, and a self-hosted proxy dials home over the config/audit grpc stream. requires the scale or enterprise plan.
	// +immutable
	// +optional
	SelfHosted *bool `json:"selfHosted,omitempty"`

	// AllowedCidrs is the ip filtering rules as cidr ranges with optional labels. when non-empty, only connections from matching ips are accepted. empty array means all ips are allowed (default). both ipv4 (e.g. 10.0.0.0/8) and ipv6 (e.g. 2001:db8::/32) are supported.
	// +optional
	AllowedCidrs []CidrEntryParameters `json:"allowedCidrs,omitempty"`

	// DefaultPolicyProfileID is the when set, passthrough/human connections are enforced against this policy profile.
	// +optional
	DefaultPolicyProfileID *string `json:"defaultPolicyProfileID,omitempty"`

	// Residency is the data-residency requirement for the project. "any" (default) lets queries be served from the nearest data-plane metro. "us" or "eu" require the serving metro to be in that jurisdiction; the proxy fails a connection closed when it is served from a metro outside the required jurisdiction, so regulated workloads never process outside their permitted region.
	// +optional
	// +kubebuilder:validation:Enum=any;us;eu
	// +kubebuilder:default=any
	Residency string `json:"residency,omitempty"`

	// AgentsDisabled is the project-level kill-switch. when true, all agent-credential connections to this project are blocked at the proxy and live agent sessions are dropped within seconds. passthrough/human connections are unaffected.
	// +optional
	AgentsDisabled *bool `json:"agentsDisabled,omitempty"`

	// Status is the project lifecycle status.
	// +optional
	// +kubebuilder:validation:Enum=active;suspended;deleted
	Status string `json:"status,omitempty"`

	// Database is the request body for registering an upstream database.
	// +kubebuilder:validation:Required
	// +immutable
	Database ProjectDatabaseSpec `json:"database"`
}

// ProjectAtProvider defines the observed state of a Project.
type ProjectAtProvider struct {
	// ID is the PgBeam project ID.
	ID string `json:"id,omitempty"`

	// ProxyHost is the proxy hostname for connecting through pgbeam (e.g., myproject.proxy.pgbeam.app).
	ProxyHost string `json:"proxyHost,omitempty"`

	// QueriesPerSecond is the maximum queries per second for this project. 0 means unlimited.
	QueriesPerSecond int `json:"queriesPerSecond,omitempty"`

	// BurstSize is the burst allowance above the steady-state rate. 0 uses queries_per_second as burst.
	BurstSize int `json:"burstSize,omitempty"`

	// MaxConnections is the maximum concurrent proxy connections. 0 means unlimited.
	MaxConnections int `json:"maxConnections,omitempty"`

	// DatabaseCount is the number of databases attached to this project.
	DatabaseCount int `json:"databaseCount,omitempty"`

	// ActiveConnections is the current active connections (latest metrics snapshot). 0 when no metrics data.
	ActiveConnections int `json:"activeConnections,omitempty"`

	// CreatedAt is the when the project was created.
	CreatedAt string `json:"createdAt,omitempty"`

	// UpdatedAt is the when the project was last updated.
	UpdatedAt string `json:"updatedAt,omitempty"`

	// PrimaryDatabaseID is the id of the primary database created with this project.
	PrimaryDatabaseID string `json:"primaryDatabaseID,omitempty"`
}

// ProjectSpec defines the desired state of a Project.
type ProjectSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       ProjectForProvider `json:"forProvider"`
}

// ProjectStatus defines the observed state of a Project.
type ProjectStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          ProjectAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// Project is a managed resource that represents a PgBeam Project.
type Project struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ProjectSpec   `json:"spec"`
	Status ProjectStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectList contains a list of Projects.
type ProjectList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Project `json:"items"`
}

// ============================================================================
// Database
// ============================================================================

// DatabaseForProvider defines the desired state of a Database.
type DatabaseForProvider struct {
	// ProjectID is the owning project id.
	// +kubebuilder:validation:Required
	// +immutable
	ProjectID string `json:"projectID"`

	// Host is the postgresql host.
	// +kubebuilder:validation:Required
	Host string `json:"host"`

	// Port is the postgresql port.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=65535
	Port int `json:"port"`

	// Name is the postgresql database name.
	// +kubebuilder:validation:Required
	Name string `json:"name"`

	// Username is the postgresql username.
	// +kubebuilder:validation:Required
	Username string `json:"username"`

	// SSLMode is the postgresql ssl connection mode.
	// +optional
	// +kubebuilder:validation:Enum=disable;allow;prefer;require;verify-ca;verify-full
	SSLMode string `json:"sslMode,omitempty"`

	// Role is the database role. primary receives writes, replicas receive reads.
	// +optional
	// +kubebuilder:validation:Enum=primary;replica
	// +kubebuilder:default=primary
	Role string `json:"role,omitempty"`

	// PoolRegion is the region where the connection pool is maintained (near the database). when set and different from the client's edge region, queries are relayed through the pool region's data plane. empty means direct connection.
	// +optional
	PoolRegion *string `json:"poolRegion,omitempty"`

	// QueryTimeoutMs is the query timeout in milliseconds. when set (> 0), the proxy sends set statement_timeout on upstream connections. 0 means disabled (default).
	// +optional
	// +kubebuilder:default=0
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:Maximum=300000
	QueryTimeoutMs *int `json:"queryTimeoutMs,omitempty"`

	// AutoReadRouting is the when enabled and replicas are configured, select queries automatically route to read replicas without requiring the @pgbeam:replica sql annotation.
	// +optional
	// +kubebuilder:default=false
	AutoReadRouting *bool `json:"autoReadRouting,omitempty"`

	// CacheConfig is the query cache configuration.
	// +optional
	CacheConfig *CacheConfigSpec `json:"cacheConfig,omitempty"`

	// PoolConfig is the connection pool configuration.
	// +optional
	PoolConfig *PoolConfigSpec `json:"poolConfig,omitempty"`

	// PasswordSecretRef is the postgresql password. stored encrypted at rest.
	// +kubebuilder:validation:Required
	PasswordSecretRef xpv1.SecretKeySelector `json:"passwordSecretRef"`
}

// DatabaseAtProvider defines the observed state of a Database.
type DatabaseAtProvider struct {
	// ID is the PgBeam database ID.
	ID string `json:"id,omitempty"`

	// ConnectionString is the connection string for connecting through pgbeam proxy. password is replaced with a placeholder.
	ConnectionString string `json:"connectionString,omitempty"`

	// CreatedAt is the when the database registration was created.
	CreatedAt string `json:"createdAt,omitempty"`

	// UpdatedAt is the when the database registration was last updated.
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// DatabaseSpec defines the desired state of a Database.
type DatabaseSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       DatabaseForProvider `json:"forProvider"`
}

// DatabaseStatus defines the observed state of a Database.
type DatabaseStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          DatabaseAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// Database is a managed resource that represents a PgBeam Database.
type Database struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DatabaseSpec   `json:"spec"`
	Status DatabaseStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DatabaseList contains a list of Databases.
type DatabaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Database `json:"items"`
}

// ============================================================================
// Replica
// ============================================================================

// ReplicaForProvider defines the desired state of a Replica.
type ReplicaForProvider struct {
	// DatabaseID is the parent database id.
	// +kubebuilder:validation:Required
	// +immutable
	DatabaseID string `json:"databaseID"`

	// Host is the postgresql replica host.
	// +kubebuilder:validation:Required
	// +immutable
	Host string `json:"host"`

	// Port is the postgresql replica port.
	// +kubebuilder:validation:Required
	// +immutable
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=65535
	Port int `json:"port"`

	// SSLMode is the postgresql ssl connection mode.
	// +immutable
	// +optional
	// +kubebuilder:validation:Enum=disable;allow;prefer;require;verify-ca;verify-full
	SSLMode string `json:"sslMode,omitempty"`
}

// ReplicaAtProvider defines the observed state of a Replica.
type ReplicaAtProvider struct {
	// ID is the PgBeam replica ID.
	ID string `json:"id,omitempty"`

	// CreatedAt is the when the replica was created.
	CreatedAt string `json:"createdAt,omitempty"`

	// UpdatedAt is the when the replica was last updated.
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// ReplicaSpec defines the desired state of a Replica.
type ReplicaSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       ReplicaForProvider `json:"forProvider"`
}

// ReplicaStatus defines the observed state of a Replica.
type ReplicaStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          ReplicaAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// Replica is a managed resource that represents a PgBeam Replica.
// All fields are immutable; any change triggers recreation.
type Replica struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ReplicaSpec   `json:"spec"`
	Status ReplicaStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ReplicaList contains a list of Replicas.
type ReplicaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Replica `json:"items"`
}

// ============================================================================
// CustomDomain
// ============================================================================

// CustomDomainForProvider defines the desired state of a CustomDomain.
type CustomDomainForProvider struct {
	// ProjectID is the owning project id.
	// +kubebuilder:validation:Required
	// +immutable
	ProjectID string `json:"projectID"`

	// Domain is the the custom domain name.
	// +kubebuilder:validation:Required
	// +immutable
	Domain string `json:"domain"`
}

// DNSInstructionsObservation dns records the user needs to create for domain verification.
type DNSInstructionsObservation struct {

	// CnameHost is the the cname record host.
	CnameHost string `json:"cnameHost,omitempty"`

	// CnameTarget is the the cname record target.
	CnameTarget string `json:"cnameTarget,omitempty"`

	// TxtHost is the the txt record host for verification.
	TxtHost string `json:"txtHost,omitempty"`

	// TxtValue is the the txt record value for verification.
	TxtValue string `json:"txtValue,omitempty"`

	// ACMECnameHost is the the cname record host for acme tls certificate issuance.
	ACMECnameHost string `json:"acmeCnameHost,omitempty"`

	// ACMECnameTarget is the the cname target for acme challenge delegation.
	ACMECnameTarget string `json:"acmeCnameTarget,omitempty"`
}

// CustomDomainAtProvider defines the observed state of a CustomDomain.
type CustomDomainAtProvider struct {
	// ID is the PgBeam custom domain ID.
	ID string `json:"id,omitempty"`

	// Verified is the whether dns ownership has been verified.
	Verified *bool `json:"verified,omitempty"`

	// VerifiedAt is the when dns verification was completed.
	VerifiedAt string `json:"verifiedAt,omitempty"`

	// TLSCertExpiry is the when the tls certificate expires.
	TLSCertExpiry string `json:"tlsCertExpiry,omitempty"`

	// DNSVerificationToken is the token value for the dns txt record verification.
	DNSVerificationToken string `json:"dnsVerificationToken,omitempty"`

	// DNSInstructions is the dns records the user needs to create for domain verification.
	DNSInstructions *DNSInstructionsObservation `json:"dnsInstructions,omitempty"`

	// CreatedAt is the when the custom domain was created.
	CreatedAt string `json:"createdAt,omitempty"`

	// UpdatedAt is the when the custom domain was last updated.
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// CustomDomainSpec defines the desired state of a CustomDomain.
type CustomDomainSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       CustomDomainForProvider `json:"forProvider"`
}

// CustomDomainStatus defines the observed state of a CustomDomain.
type CustomDomainStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          CustomDomainAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// CustomDomain is a managed resource that represents a PgBeam Custom Domain.
// All fields are immutable; any change triggers recreation.
type CustomDomain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CustomDomainSpec   `json:"spec"`
	Status CustomDomainStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomDomainList contains a list of CustomDomains.
type CustomDomainList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomDomain `json:"items"`
}

// ============================================================================
// CacheRule
// ============================================================================

// CacheRuleForProvider defines the desired state of a CacheRule.
type CacheRuleForProvider struct {
	// QueryHash is the queryhash path parameter.
	// +kubebuilder:validation:Required
	// +immutable
	QueryHash string `json:"queryHash"`

	// DatabaseID is the databaseid path parameter.
	// +kubebuilder:validation:Required
	// +immutable
	DatabaseID string `json:"databaseID"`

	// ProjectID is the projectid path parameter.
	// +kubebuilder:validation:Required
	// +immutable
	ProjectID string `json:"projectID"`

	// CacheEnabled is the whether caching is enabled for this query shape.
	// +kubebuilder:validation:Required
	CacheEnabled bool `json:"cacheEnabled"`

	// CacheTTLSeconds is the ttl override in seconds. null means use project default.
	// +optional
	// +kubebuilder:validation:Minimum=0
	CacheTTLSeconds *int `json:"cacheTTLSeconds,omitempty"`

	// CacheSWRSeconds is the swr override in seconds. null means use project default.
	// +optional
	// +kubebuilder:validation:Minimum=0
	CacheSWRSeconds *int `json:"cacheSWRSeconds,omitempty"`
}

// CacheRuleAtProvider defines the observed state of a CacheRule.
type CacheRuleAtProvider struct {
	// ID is the PgBeam cache rule ID.
	ID string `json:"id,omitempty"`

	// QueryHash is the xxhash64 hex of the normalized sql.
	QueryHash string `json:"queryHash,omitempty"`

	// NormalizedSQL is the sql with literals replaced by $n placeholders.
	NormalizedSQL string `json:"normalizedSQL,omitempty"`

	// QueryType is the query classification.
	QueryType string `json:"queryType,omitempty"`

	// CallCount is the total number of executions observed.
	CallCount int64 `json:"callCount,omitempty"`

	// AvgLatencyMs is the average query latency in milliseconds.
	AvgLatencyMs float64 `json:"avgLatencyMs,omitempty"`

	// P95LatencyMs is the 95th percentile latency in milliseconds.
	P95LatencyMs float64 `json:"p95LatencyMs,omitempty"`

	// AvgResponseBytes is the average response size in bytes.
	AvgResponseBytes int64 `json:"avgResponseBytes,omitempty"`

	// StabilityRate is the response stability rate (0.0 to 1.0). higher means more stable.
	StabilityRate float64 `json:"stabilityRate,omitempty"`

	// Recommendation is the cache recommendation based on frequency, latency, and stability.
	Recommendation string `json:"recommendation,omitempty"`

	// FirstSeenAt is the when this query was first observed.
	FirstSeenAt string `json:"firstSeenAt,omitempty"`

	// LastSeenAt is the when this query was last observed.
	LastSeenAt string `json:"lastSeenAt,omitempty"`
}

// CacheRuleSpec defines the desired state of a CacheRule.
type CacheRuleSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       CacheRuleForProvider `json:"forProvider"`
}

// CacheRuleStatus defines the observed state of a CacheRule.
type CacheRuleStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          CacheRuleAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// CacheRule is a managed resource that represents a PgBeam Cache Rule.
// Deletion is a soft delete that sets cache_enabled=false.
type CacheRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CacheRuleSpec   `json:"spec"`
	Status CacheRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CacheRuleList contains a list of CacheRules.
type CacheRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CacheRule `json:"items"`
}

// ============================================================================
// SpendLimit
// ============================================================================

// SpendLimitForProvider defines the desired state of a SpendLimit.
type SpendLimitForProvider struct {
	// OrgID is the orgid path parameter.
	// +kubebuilder:validation:Required
	// +immutable
	OrgID string `json:"orgID"`

	// SpendLimit is the monthly spend limit in dollars. null means no limit.
	// +optional
	SpendLimit *float64 `json:"spendLimit,omitempty"`
}

// PlanLimitsObservation effective usage limits enforced for an organization plan.
type PlanLimitsObservation struct {

	// QueriesPerDay is the maximum queries per day across all projects. 0 means unlimited.
	QueriesPerDay int64 `json:"queriesPerDay,omitempty"`

	// MaxProjects is the maximum number of active projects.
	MaxProjects int `json:"maxProjects,omitempty"`

	// MaxDatabases is the maximum databases per project.
	MaxDatabases int `json:"maxDatabases,omitempty"`

	// MaxConnections is the maximum concurrent connections per project.
	MaxConnections int `json:"maxConnections,omitempty"`

	// QueriesPerSecond is the maximum queries per second per project.
	QueriesPerSecond int `json:"queriesPerSecond,omitempty"`

	// BytesPerMonth is the monthly data transfer quota in bytes. 0 means unlimited.
	BytesPerMonth int64 `json:"bytesPerMonth,omitempty"`

	// MaxQueryShapes is the maximum query shapes in cache rules. 0 means unlimited.
	MaxQueryShapes int `json:"maxQueryShapes,omitempty"`

	// IncludedSeats is the number of seats included in the plan.
	IncludedSeats int `json:"includedSeats,omitempty"`

	// MaxAgentCredentials is the maximum agent credentials per organization. 0 means unlimited.
	MaxAgentCredentials int `json:"maxAgentCredentials,omitempty"`

	// AuditRetentionDays is the agent audit-log retention window in days.
	AuditRetentionDays int `json:"auditRetentionDays,omitempty"`

	// SandboxMaxBranches is the maximum concurrently active instant (sandbox) branches. 0 means no limit.
	SandboxMaxBranches int `json:"sandboxMaxBranches,omitempty"`

	// SandboxMaxUpstreamBytes is the maximum upstream source-database size a sandbox base sync accepts, in bytes. 0 means no limit.
	SandboxMaxUpstreamBytes int64 `json:"sandboxMaxUpstreamBytes,omitempty"`

	// SandboxIdleSeconds is the idle time before an instant (sandbox) branch scales to zero, in seconds.
	SandboxIdleSeconds int `json:"sandboxIdleSeconds,omitempty"`

	// SandboxTTLSeconds is the lifetime of an instant (sandbox) branch before the ttl sweep discards it, in seconds.
	SandboxTTLSeconds int `json:"sandboxTTLSeconds,omitempty"`
}

// SpendLimitAtProvider defines the observed state of a SpendLimit.
type SpendLimitAtProvider struct {
	// ID is the PgBeam spend limit ID.
	ID string `json:"id,omitempty"`

	// OrgID is the organization identifier the plan applies to.
	OrgID string `json:"orgID,omitempty"`

	// Plan is the current plan tier.
	Plan string `json:"plan,omitempty"`

	// BillingProvider is the which billing provider manages this organization's subscription.
	BillingProvider string `json:"billingProvider,omitempty"`

	// SubscriptionStatus is the stripe subscription status.
	SubscriptionStatus string `json:"subscriptionStatus,omitempty"`

	// CurrentPeriodEnd is the end of current billing period.
	CurrentPeriodEnd string `json:"currentPeriodEnd,omitempty"`

	// Enabled is the whether the organization billing is active (false = suspended).
	Enabled *bool `json:"enabled,omitempty"`

	// CustomPricing is the whether the organization has custom enterprise pricing.
	CustomPricing *bool `json:"customPricing,omitempty"`

	// SpendCapped is the whether the organization has hit its spend limit and agent access is paused at the proxy. lifts automatically when usage resets for the new billing period, or immediately when the spend limit is raised or removed.
	SpendCapped *bool `json:"spendCapped,omitempty"`

	// SpendCappedAt is the when the spend cap was applied. null when not capped.
	SpendCappedAt string `json:"spendCappedAt,omitempty"`

	// Limits is the effective usage limits enforced for an organization plan.
	Limits *PlanLimitsObservation `json:"limits,omitempty"`

	// CreatedAt is the when the billing record was created.
	CreatedAt string `json:"createdAt,omitempty"`

	// UpdatedAt is the when the billing record was last updated.
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// SpendLimitSpec defines the desired state of a SpendLimit.
type SpendLimitSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       SpendLimitForProvider `json:"forProvider"`
}

// SpendLimitStatus defines the observed state of a SpendLimit.
type SpendLimitStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          SpendLimitAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// SpendLimit is a managed resource that represents a PgBeam Spend Limit.
// Deletion is a soft delete that sets spend_limit=null.
type SpendLimit struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SpendLimitSpec   `json:"spec"`
	Status SpendLimitStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SpendLimitList contains a list of SpendLimits.
type SpendLimitList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SpendLimit `json:"items"`
}

// ============================================================================
// AgentCredential
// ============================================================================

// AgentCredentialForProvider defines the desired state of a AgentCredential.
type AgentCredentialForProvider struct {
	// ProjectID is the owning project id.
	// +kubebuilder:validation:Required
	// +immutable
	ProjectID string `json:"projectID"`

	// PolicyProfileID is the policy profile enforced for this credential.
	// +kubebuilder:validation:Required
	// +immutable
	PolicyProfileID string `json:"policyProfileID"`

	// Name is the human-readable label for the credential.
	// +kubebuilder:validation:Required
	// +immutable
	Name string `json:"name"`

	// Status is the lifecycle status of the credential.
	// +optional
	// +kubebuilder:validation:Enum=active;disabled;revoked
	Status string `json:"status,omitempty"`

	// PrincipalType is the whether this credential represents an autonomous agent or a human operator.
	// +immutable
	// +optional
	// +kubebuilder:validation:Enum=agent;human
	// +kubebuilder:default=agent
	PrincipalType string `json:"principalType,omitempty"`

	// ExpiresAt is the when the credential expires and becomes unusable. null means it never expires. enforcement is fail-closed in the proxy the instant this time passes, before any cleanup sweep runs.
	// +immutable
	// +optional
	ExpiresAt string `json:"expiresAt,omitempty"`
}

// AgentCredentialAtProvider defines the observed state of a AgentCredential.
type AgentCredentialAtProvider struct {
	// ID is the PgBeam agent credential ID.
	ID string `json:"id,omitempty"`

	// PgUsername is the the postgres username this credential presents to the proxy.
	PgUsername string `json:"pgUsername,omitempty"`

	// AuthMethod is the postgres auth method the proxy presents for this credential.
	AuthMethod string `json:"authMethod,omitempty"`

	// LastUsedAt is the when the credential was last used to connect, if ever.
	LastUsedAt string `json:"lastUsedAt,omitempty"`

	// CreatedAt is the when the credential was created.
	CreatedAt string `json:"createdAt,omitempty"`

	// UpdatedAt is the when the credential was last updated.
	UpdatedAt string `json:"updatedAt,omitempty"`

	// McpURL is the hosted agent-database mcp endpoint for this project. use with the mcp_token as a bearer token.
	McpURL string `json:"mcpURL,omitempty"`
}

// AgentCredentialSpec defines the desired state of a AgentCredential.
type AgentCredentialSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       AgentCredentialForProvider `json:"forProvider"`
}

// AgentCredentialStatus defines the observed state of a AgentCredential.
type AgentCredentialStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          AgentCredentialAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// AgentCredential is a managed resource that represents a PgBeam Agent Credential.
type AgentCredential struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AgentCredentialSpec   `json:"spec"`
	Status AgentCredentialStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AgentCredentialList contains a list of AgentCredentials.
type AgentCredentialList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AgentCredential `json:"items"`
}

// ============================================================================
// PolicyProfile
// ============================================================================

// MaskingRuleParameters is one entry of column masking rules applied to query results.
type MaskingRuleParameters struct {

	// Table is the relation name, optionally schema-qualified (e.g. "public.users" or "users").
	// +kubebuilder:validation:Required
	Table string `json:"table"`

	// Column is the column to mask.
	// +kubebuilder:validation:Required
	Column string `json:"column"`

	// Kind is the how to mask. redact replaces with a token, null returns null, hash returns a sha-256 hex.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=redact;null;hash
	Kind string `json:"kind"`
}

// RowFilterParameters is one entry of per-relation row filters anded into agent reads.
type RowFilterParameters struct {

	// Table is the relation name, optionally schema-qualified (e.g. "public.orders").
	// +kubebuilder:validation:Required
	Table string `json:"table"`

	// Predicate is the raw sql boolean expression anded into where for this relation.
	// +kubebuilder:validation:Required
	Predicate string `json:"predicate"`
}

// StatementRulesSpec defines the per-statement-kind allow/deny lists. empty allow means all kinds permitted by the access mode.
type StatementRulesSpec struct {

	// Allow is the allowed statement kinds (select, insert, update, delete, ddl, copy, set, show, explain, transaction).
	// +optional
	Allow *[]string `json:"allow,omitempty"`

	// Deny is the denied statement kinds (takes precedence over allow).
	// +optional
	Deny *[]string `json:"deny,omitempty"`
}

// PolicyProfileForProvider defines the desired state of a PolicyProfile.
type PolicyProfileForProvider struct {
	// ProjectID is the owning project id.
	// +kubebuilder:validation:Required
	// +immutable
	ProjectID string `json:"projectID"`

	// Name is the human-readable name for the policy profile.
	// +kubebuilder:validation:Required
	Name string `json:"name"`

	// AccessMode is the read_only blocks all data and schema mutations.
	// +optional
	// +kubebuilder:validation:Enum=read_only;read_write
	AccessMode string `json:"accessMode,omitempty"`

	// StatementRules is the per-statement-kind allow/deny lists. empty allow means all kinds permitted by the access mode.
	// +optional
	StatementRules *StatementRulesSpec `json:"statementRules,omitempty"`

	// TableAllowlist is the if non-empty, only these relations are reachable. entries are schema-qualified (billing.orders) or bare (orders); a bare entry grants the public schema only, so the same table name in another schema must be listed in full.
	// +optional
	TableAllowlist []string `json:"tableAllowlist,omitempty"`

	// TableDenylist is the relations explicitly blocked (takes precedence over the allowlist). a bare entry blocks that relation in every schema.
	// +optional
	TableDenylist []string `json:"tableDenylist,omitempty"`

	// MaskingRules is the column masking rules applied to query results.
	// +optional
	MaskingRules []MaskingRuleParameters `json:"maskingRules,omitempty"`

	// BudgetQueriesPerHour is the max queries per rolling hour window. 0 means unlimited.
	// +optional
	// +kubebuilder:default=0
	BudgetQueriesPerHour *int `json:"budgetQueriesPerHour,omitempty"`

	// BudgetQueriesPerDay is the max queries per day window. 0 means unlimited.
	// +optional
	// +kubebuilder:default=0
	BudgetQueriesPerDay *int `json:"budgetQueriesPerDay,omitempty"`

	// MaxRows is the max rows returned per query. 0 means unlimited.
	// +optional
	// +kubebuilder:default=0
	MaxRows *int `json:"maxRows,omitempty"`

	// StatementTimeoutMs is the upstream statement timeout for agent sessions. 0 uses the project default.
	// +optional
	// +kubebuilder:default=0
	StatementTimeoutMs *int `json:"statementTimeoutMs,omitempty"`

	// RowFilters is the per-relation row filters anded into agent reads.
	// +optional
	RowFilters []RowFilterParameters `json:"rowFilters,omitempty"`

	// WriteMode is the how writes are handled. normal commits, rollback auto-rolls back, sandbox routes to an ephemeral branch.
	// +optional
	// +kubebuilder:validation:Enum=normal;rollback;sandbox
	// +kubebuilder:default=normal
	WriteMode string `json:"writeMode,omitempty"`

	// ApprovalMode is the which statement classes require human approval before execution.
	// +optional
	// +kubebuilder:validation:Enum=off;writes;ddl;all
	// +kubebuilder:default=off
	ApprovalMode string `json:"approvalMode,omitempty"`

	// ApprovalAutoMaxRows is the statements touching at most this many rows are auto-approved. 0 means none.
	// +optional
	// +kubebuilder:default=0
	// +kubebuilder:validation:Minimum=0
	ApprovalAutoMaxRows *int `json:"approvalAutoMaxRows,omitempty"`

	// ApprovalTimeoutSeconds is the how long a held statement waits for a decision before expiring.
	// +optional
	// +kubebuilder:default=300
	// +kubebuilder:validation:Minimum=0
	ApprovalTimeoutSeconds *int `json:"approvalTimeoutSeconds,omitempty"`

	// MigrationSafety is the migration safety mode. warn surfaces findings, block refuses unsafe ddl.
	// +optional
	// +kubebuilder:validation:Enum=off;warn;block
	// +kubebuilder:default=off
	MigrationSafety string `json:"migrationSafety,omitempty"`

	// EgressBytesPerDay is the per-day egress budget in bytes. 0 means unlimited.
	// +optional
	// +kubebuilder:default=0
	// +kubebuilder:validation:Minimum=0
	EgressBytesPerDay *int64 `json:"egressBytesPerDay,omitempty"`

	// MaxAffectedRows is the hard cap on rows a single write (insert/update/delete) may affect. a write whose affected-row count would exceed this is executed inside a transaction, checked, and rolled back so nothing persists, then blocked. enforced independently of human approval. 0 means unlimited.
	// +optional
	// +kubebuilder:default=0
	// +kubebuilder:validation:Minimum=0
	MaxAffectedRows *int `json:"maxAffectedRows,omitempty"`
}

// PolicyProfileAtProvider defines the observed state of a PolicyProfile.
type PolicyProfileAtProvider struct {
	// ID is the PgBeam policy profile ID.
	ID string `json:"id,omitempty"`

	// CreatedAt is the when the policy profile was created.
	CreatedAt string `json:"createdAt,omitempty"`

	// UpdatedAt is the when the policy profile was last updated.
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// PolicyProfileSpec defines the desired state of a PolicyProfile.
type PolicyProfileSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       PolicyProfileForProvider `json:"forProvider"`
}

// PolicyProfileStatus defines the observed state of a PolicyProfile.
type PolicyProfileStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          PolicyProfileAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// PolicyProfile is a managed resource that represents a PgBeam Policy Profile.
type PolicyProfile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PolicyProfileSpec   `json:"spec"`
	Status PolicyProfileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyProfileList contains a list of PolicyProfiles.
type PolicyProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyProfile `json:"items"`
}

// ============================================================================
// WebhookEndpoint
// ============================================================================

// WebhookEndpointForProvider defines the desired state of a WebhookEndpoint.
type WebhookEndpointForProvider struct {
	// ProjectID is the owning project id.
	// +kubebuilder:validation:Required
	// +immutable
	ProjectID string `json:"projectID"`

	// URL is the https endpoint that receives event deliveries.
	// +kubebuilder:validation:Required
	URL string `json:"url"`

	// Format is the payload format for delivered events.
	// +optional
	// +kubebuilder:validation:Enum=json;splunk_hec;datadog;elastic
	Format string `json:"format,omitempty"`

	// EventTypes is the event types to deliver. empty means all events.
	// +optional
	EventTypes []string `json:"eventTypes,omitempty"`

	// Enabled is the whether deliveries are active for this endpoint.
	// +optional
	Enabled *bool `json:"enabled,omitempty"`

	// Description is the human-readable label for the endpoint.
	// +optional
	Description *string `json:"description,omitempty"`

	// SecretSecretRef is the shared secret used to sign delivery payloads. write-only.
	// +optional
	// +kubebuilder:validation:Required
	SecretSecretRef xpv1.SecretKeySelector `json:"secretSecretRef"`
}

// WebhookEndpointAtProvider defines the observed state of a WebhookEndpoint.
type WebhookEndpointAtProvider struct {
	// ID is the PgBeam webhook endpoint ID.
	ID string `json:"id,omitempty"`

	// CreatedAt is the when the endpoint was created.
	CreatedAt string `json:"createdAt,omitempty"`

	// UpdatedAt is the when the endpoint was last updated.
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// WebhookEndpointSpec defines the desired state of a WebhookEndpoint.
type WebhookEndpointSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       WebhookEndpointForProvider `json:"forProvider"`
}

// WebhookEndpointStatus defines the observed state of a WebhookEndpoint.
type WebhookEndpointStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          WebhookEndpointAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// WebhookEndpoint is a managed resource that represents a PgBeam Webhook Endpoint.
type WebhookEndpoint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   WebhookEndpointSpec   `json:"spec"`
	Status WebhookEndpointStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WebhookEndpointList contains a list of WebhookEndpoints.
type WebhookEndpointList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WebhookEndpoint `json:"items"`
}

// ============================================================================
// SelfHostEnrollment
// ============================================================================

// SelfHostEnrollmentForProvider defines the desired state of a SelfHostEnrollment.
type SelfHostEnrollmentForProvider struct {
	// OrgID is the organization that owns this enrollment.
	// +kubebuilder:validation:Required
	// +immutable
	OrgID string `json:"orgID"`

	// RegionLabel is the operator-supplied label for where the proxy runs (informational).
	// +immutable
	// +optional
	RegionLabel *string `json:"regionLabel,omitempty"`

	// Description is the optional human-readable note.
	// +immutable
	// +optional
	Description *string `json:"description,omitempty"`

	// ExpiresAt is the when the enrollment token expires and stops authenticating new proxy connections. null means it never expires. enforcement is fail-closed at the grpc auth gate the instant this time passes.
	// +immutable
	// +optional
	ExpiresAt string `json:"expiresAt,omitempty"`
}

// SelfHostEnrollmentAtProvider defines the observed state of a SelfHostEnrollment.
type SelfHostEnrollmentAtProvider struct {
	// ID is the PgBeam self host enrollment ID.
	ID string `json:"id,omitempty"`

	// CreatedBy is the user id that created the enrollment.
	CreatedBy string `json:"createdBy,omitempty"`

	// CreatedAt is the when the enrollment was created.
	CreatedAt string `json:"createdAt,omitempty"`

	// LastSeenAt is the last time a proxy authenticated with this enrollment.
	LastSeenAt string `json:"lastSeenAt,omitempty"`

	// RevokedAt is the when the enrollment was revoked. null means active.
	RevokedAt string `json:"revokedAt,omitempty"`
}

// SelfHostEnrollmentSpec defines the desired state of a SelfHostEnrollment.
type SelfHostEnrollmentSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       SelfHostEnrollmentForProvider `json:"forProvider"`
}

// SelfHostEnrollmentStatus defines the observed state of a SelfHostEnrollment.
type SelfHostEnrollmentStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          SelfHostEnrollmentAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// SelfHostEnrollment is a managed resource that represents a PgBeam Self Host Enrollment.
// All fields are immutable; any change triggers recreation.
type SelfHostEnrollment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SelfHostEnrollmentSpec   `json:"spec"`
	Status SelfHostEnrollmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SelfHostEnrollmentList contains a list of SelfHostEnrollments.
type SelfHostEnrollmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SelfHostEnrollment `json:"items"`
}

// ============================================================================
// Honeytoken
// ============================================================================

// HoneytokenForProvider defines the desired state of a Honeytoken.
type HoneytokenForProvider struct {
	// ProjectID is the project the honeytoken belongs to.
	// +kubebuilder:validation:Required
	// +immutable
	ProjectID string `json:"projectID"`

	// SchemaName is the optional schema. null matches the unqualified/public form, mirroring the relation allowlist normalization.
	// +optional
	SchemaName *string `json:"schemaName,omitempty"`

	// RelationName is the relation (table or view) name of the decoy.
	// +kubebuilder:validation:Required
	RelationName string `json:"relationName"`

	// Action is the response when tripped. audit_only blocks the statement, records the event, and fires webhooks. kill additionally disables the tripping credential via the kill-switch.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=audit_only;kill
	Action string `json:"action"`
}

// HoneytokenAtProvider defines the observed state of a Honeytoken.
type HoneytokenAtProvider struct {
	// ID is the PgBeam honeytoken ID.
	ID string `json:"id,omitempty"`

	// CreatedAt is the when the honeytoken was registered.
	CreatedAt string `json:"createdAt,omitempty"`

	// UpdatedAt is the when the honeytoken was last updated.
	UpdatedAt string `json:"updatedAt,omitempty"`
}

// HoneytokenSpec defines the desired state of a Honeytoken.
type HoneytokenSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       HoneytokenForProvider `json:"forProvider"`
}

// HoneytokenStatus defines the observed state of a Honeytoken.
type HoneytokenStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          HoneytokenAtProvider `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories=crossplane;managed;pgbeam
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// Honeytoken is a managed resource that represents a PgBeam Honeytoken.
type Honeytoken struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   HoneytokenSpec   `json:"spec"`
	Status HoneytokenStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HoneytokenList contains a list of Honeytokens.
type HoneytokenList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Honeytoken `json:"items"`
}
