//go:build !ignore_autogenerated

// Code generated by hand (normally controller-gen). DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ProviderConfig) DeepCopyInto(out *ProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ProviderConfig) DeepCopy() *ProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *ProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ProviderConfigList) DeepCopyInto(out *ProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ProviderConfigList) DeepCopy() *ProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *ProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ProviderConfigSpec) DeepCopyInto(out *ProviderConfigSpec) {
	*out = *in
	out.APIKeySecretRef = in.APIKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ProviderConfigSpec) DeepCopy() *ProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ProviderConfigUsage) DeepCopyInto(out *ProviderConfigUsage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.ProviderConfigUsage.DeepCopyInto(&out.ProviderConfigUsage)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ProviderConfigUsage) DeepCopy() *ProviderConfigUsage {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *ProviderConfigUsage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ProviderConfigUsageList) DeepCopyInto(out *ProviderConfigUsageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProviderConfigUsage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ProviderConfigUsageList) DeepCopy() *ProviderConfigUsageList {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigUsageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *ProviderConfigUsageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ============================================================================
// Project
// ============================================================================

// DeepCopyInto is an autogenerated deepcopy function.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Project, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *ProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ProjectForProvider) DeepCopyInto(out *ProjectForProvider) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.QueriesPerSecond != nil {
		in, out := &in.QueriesPerSecond, &out.QueriesPerSecond
		*out = new(int32)
		**out = **in
	}
	if in.BurstSize != nil {
		in, out := &in.BurstSize, &out.BurstSize
		*out = new(int32)
		**out = **in
	}
	if in.MaxConnections != nil {
		in, out := &in.MaxConnections, &out.MaxConnections
		*out = new(int32)
		**out = **in
	}
	in.Database.DeepCopyInto(&out.Database)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ProjectForProvider) DeepCopy() *ProjectForProvider {
	if in == nil {
		return nil
	}
	out := new(ProjectForProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ProjectAtProvider) DeepCopyInto(out *ProjectAtProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ProjectAtProvider) DeepCopy() *ProjectAtProvider {
	if in == nil {
		return nil
	}
	out := new(ProjectAtProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ProjectDatabaseSpec) DeepCopyInto(out *ProjectDatabaseSpec) {
	*out = *in
	out.PasswordSecretRef = in.PasswordSecretRef
	if in.PoolRegion != nil {
		in, out := &in.PoolRegion, &out.PoolRegion
		*out = new(string)
		**out = **in
	}
	if in.CacheConfig != nil {
		in, out := &in.CacheConfig, &out.CacheConfig
		*out = new(CacheConfigSpec)
		**out = **in
	}
	if in.PoolConfig != nil {
		in, out := &in.PoolConfig, &out.PoolConfig
		*out = new(PoolConfigSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ProjectDatabaseSpec) DeepCopy() *ProjectDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CacheConfigSpec) DeepCopyInto(out *CacheConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CacheConfigSpec) DeepCopy() *CacheConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CacheConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *PoolConfigSpec) DeepCopyInto(out *PoolConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *PoolConfigSpec) DeepCopy() *PoolConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PoolConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// ============================================================================
// Database
// ============================================================================

// DeepCopyInto is an autogenerated deepcopy function.
func (in *Database) DeepCopyInto(out *Database) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *Database) DeepCopy() *Database {
	if in == nil {
		return nil
	}
	out := new(Database)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *Database) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DatabaseList) DeepCopyInto(out *DatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Database, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DatabaseList) DeepCopy() *DatabaseList {
	if in == nil {
		return nil
	}
	out := new(DatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *DatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DatabaseStatus) DeepCopyInto(out *DatabaseStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DatabaseStatus) DeepCopy() *DatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DatabaseForProvider) DeepCopyInto(out *DatabaseForProvider) {
	*out = *in
	out.PasswordSecretRef = in.PasswordSecretRef
	if in.PoolRegion != nil {
		in, out := &in.PoolRegion, &out.PoolRegion
		*out = new(string)
		**out = **in
	}
	if in.CacheConfig != nil {
		in, out := &in.CacheConfig, &out.CacheConfig
		*out = new(CacheConfigSpec)
		**out = **in
	}
	if in.PoolConfig != nil {
		in, out := &in.PoolConfig, &out.PoolConfig
		*out = new(PoolConfigSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DatabaseForProvider) DeepCopy() *DatabaseForProvider {
	if in == nil {
		return nil
	}
	out := new(DatabaseForProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DatabaseAtProvider) DeepCopyInto(out *DatabaseAtProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DatabaseAtProvider) DeepCopy() *DatabaseAtProvider {
	if in == nil {
		return nil
	}
	out := new(DatabaseAtProvider)
	in.DeepCopyInto(out)
	return out
}

// ============================================================================
// Replica
// ============================================================================

// DeepCopyInto is an autogenerated deepcopy function.
func (in *Replica) DeepCopyInto(out *Replica) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *Replica) DeepCopy() *Replica {
	if in == nil {
		return nil
	}
	out := new(Replica)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *Replica) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ReplicaList) DeepCopyInto(out *ReplicaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Replica, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ReplicaList) DeepCopy() *ReplicaList {
	if in == nil {
		return nil
	}
	out := new(ReplicaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *ReplicaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ReplicaSpec) DeepCopyInto(out *ReplicaSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ReplicaSpec) DeepCopy() *ReplicaSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ReplicaStatus) DeepCopyInto(out *ReplicaStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ReplicaStatus) DeepCopy() *ReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ReplicaForProvider) DeepCopyInto(out *ReplicaForProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ReplicaForProvider) DeepCopy() *ReplicaForProvider {
	if in == nil {
		return nil
	}
	out := new(ReplicaForProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ReplicaAtProvider) DeepCopyInto(out *ReplicaAtProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ReplicaAtProvider) DeepCopy() *ReplicaAtProvider {
	if in == nil {
		return nil
	}
	out := new(ReplicaAtProvider)
	in.DeepCopyInto(out)
	return out
}

// ============================================================================
// CustomDomain
// ============================================================================

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CustomDomain) DeepCopyInto(out *CustomDomain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CustomDomain) DeepCopy() *CustomDomain {
	if in == nil {
		return nil
	}
	out := new(CustomDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *CustomDomain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CustomDomainList) DeepCopyInto(out *CustomDomainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CustomDomainList) DeepCopy() *CustomDomainList {
	if in == nil {
		return nil
	}
	out := new(CustomDomainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *CustomDomainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CustomDomainSpec) DeepCopyInto(out *CustomDomainSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CustomDomainSpec) DeepCopy() *CustomDomainSpec {
	if in == nil {
		return nil
	}
	out := new(CustomDomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CustomDomainStatus) DeepCopyInto(out *CustomDomainStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CustomDomainStatus) DeepCopy() *CustomDomainStatus {
	if in == nil {
		return nil
	}
	out := new(CustomDomainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CustomDomainForProvider) DeepCopyInto(out *CustomDomainForProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CustomDomainForProvider) DeepCopy() *CustomDomainForProvider {
	if in == nil {
		return nil
	}
	out := new(CustomDomainForProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CustomDomainAtProvider) DeepCopyInto(out *CustomDomainAtProvider) {
	*out = *in
	if in.DNSInstructions != nil {
		in, out := &in.DNSInstructions, &out.DNSInstructions
		*out = new(DNSInstructionsObservation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CustomDomainAtProvider) DeepCopy() *CustomDomainAtProvider {
	if in == nil {
		return nil
	}
	out := new(CustomDomainAtProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DNSInstructionsObservation) DeepCopyInto(out *DNSInstructionsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DNSInstructionsObservation) DeepCopy() *DNSInstructionsObservation {
	if in == nil {
		return nil
	}
	out := new(DNSInstructionsObservation)
	in.DeepCopyInto(out)
	return out
}

// ============================================================================
// CacheRule
// ============================================================================

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CacheRule) DeepCopyInto(out *CacheRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CacheRule) DeepCopy() *CacheRule {
	if in == nil {
		return nil
	}
	out := new(CacheRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *CacheRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CacheRuleList) DeepCopyInto(out *CacheRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CacheRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CacheRuleList) DeepCopy() *CacheRuleList {
	if in == nil {
		return nil
	}
	out := new(CacheRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *CacheRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CacheRuleSpec) DeepCopyInto(out *CacheRuleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CacheRuleSpec) DeepCopy() *CacheRuleSpec {
	if in == nil {
		return nil
	}
	out := new(CacheRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CacheRuleStatus) DeepCopyInto(out *CacheRuleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CacheRuleStatus) DeepCopy() *CacheRuleStatus {
	if in == nil {
		return nil
	}
	out := new(CacheRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CacheRuleForProvider) DeepCopyInto(out *CacheRuleForProvider) {
	*out = *in
	if in.CacheTTLSeconds != nil {
		in, out := &in.CacheTTLSeconds, &out.CacheTTLSeconds
		*out = new(int)
		**out = **in
	}
	if in.CacheSWRSeconds != nil {
		in, out := &in.CacheSWRSeconds, &out.CacheSWRSeconds
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CacheRuleForProvider) DeepCopy() *CacheRuleForProvider {
	if in == nil {
		return nil
	}
	out := new(CacheRuleForProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CacheRuleAtProvider) DeepCopyInto(out *CacheRuleAtProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CacheRuleAtProvider) DeepCopy() *CacheRuleAtProvider {
	if in == nil {
		return nil
	}
	out := new(CacheRuleAtProvider)
	in.DeepCopyInto(out)
	return out
}

// ============================================================================
// SpendLimit
// ============================================================================

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SpendLimit) DeepCopyInto(out *SpendLimit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SpendLimit) DeepCopy() *SpendLimit {
	if in == nil {
		return nil
	}
	out := new(SpendLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *SpendLimit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SpendLimitList) DeepCopyInto(out *SpendLimitList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpendLimit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SpendLimitList) DeepCopy() *SpendLimitList {
	if in == nil {
		return nil
	}
	out := new(SpendLimitList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *SpendLimitList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SpendLimitSpec) DeepCopyInto(out *SpendLimitSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SpendLimitSpec) DeepCopy() *SpendLimitSpec {
	if in == nil {
		return nil
	}
	out := new(SpendLimitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SpendLimitStatus) DeepCopyInto(out *SpendLimitStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SpendLimitStatus) DeepCopy() *SpendLimitStatus {
	if in == nil {
		return nil
	}
	out := new(SpendLimitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SpendLimitForProvider) DeepCopyInto(out *SpendLimitForProvider) {
	*out = *in
	if in.SpendLimit != nil {
		in, out := &in.SpendLimit, &out.SpendLimit
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SpendLimitForProvider) DeepCopy() *SpendLimitForProvider {
	if in == nil {
		return nil
	}
	out := new(SpendLimitForProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SpendLimitAtProvider) DeepCopyInto(out *SpendLimitAtProvider) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.CustomPricing != nil {
		in, out := &in.CustomPricing, &out.CustomPricing
		*out = new(bool)
		**out = **in
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(PlanLimitsObservation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SpendLimitAtProvider) DeepCopy() *SpendLimitAtProvider {
	if in == nil {
		return nil
	}
	out := new(SpendLimitAtProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *PlanLimitsObservation) DeepCopyInto(out *PlanLimitsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *PlanLimitsObservation) DeepCopy() *PlanLimitsObservation {
	if in == nil {
		return nil
	}
	out := new(PlanLimitsObservation)
	in.DeepCopyInto(out)
	return out
}
